// js/progress.js — lớp vỏ DUY NHẤT quanh xương sống.
//
// KHÔNG tự lưu trạng thái. KHÔNG tự gửi mạng. Mọi thứ đi qua Spine.
// Tệp này là chỗ duy nhất trong trang được import core/.

import { Spine } from '/core/spine.js';
import { Identity } from '/core/identity.js';
import { RULES } from '/core/config.js';
import { NAV } from '/js/data.js';

let authGateRendered = false;

export const Portal = {
  spine: Spine,

  /**
   * Gọi ở dòng đầu mọi app.js.
   *   const boot = await Portal.boot({ module:'grammar', unit:null, tab:'practice' });
   * Trả về { ok } — false nghĩa là đang hiện cổng nhập mã hoặc lỗi lưu trữ, app.js dừng lại.
   */
  async boot({ module = null, unit = null, tab = 'home' } = {}) {
    const r = await Spine.init();

    if (!r.ok) {
      const main = document.getElementById('main');
      if (main) {
        main.innerHTML = `
          <div class="panel" style="text-align:center; padding: 28px 16px;">
            <h2 style="color:var(--crit); margin-top:0;">⚠️ Progress cannot be saved</h2>
            <p>${r.error || 'Your browser is blocking saved data. Please turn off private browsing and open the page again.'}</p>
            <button class="btn" onclick="location.reload()">Try again</button>
          </div>
        `;
      }
      return { ok: false };
    }

    if (r.needIdentity) {
      Portal.renderTabbar(tab);
      Portal.renderAuthGate({ module, unit, tab });
      return { ok: false };
    }

    Portal.renderTabbar(tab);
    Portal.renderHud();

    const hudEl = document.getElementById('hud');
    if (hudEl) hudEl.removeAttribute('hidden');

    if (module) {
      Spine.openModule(module, unit);
    }

    return { ok: true };
  },

  /**
   * Chỉ đọc mã đã lưu, KHÔNG khởi động xương sống, KHÔNG ghi log.
   * Trả về 'student' | 'teacher' | 'guest'. Dùng cho cổng khoá §9.2.
   */
  role() {
    const id = Spine.id;
    if (!id) return 'guest';
    return /^GV-/i.test(id) ? 'teacher' : 'student';
  },

  /**
   * Vẽ thanh HUD trạng thái (Cấp độ, Thanh XP, Chuỗi đúng, Chờ gửi).
   */
  renderHud() {
    const el = document.getElementById('hud');
    if (!el || !Spine.isReady) return;

    const m = Spine.metrics;
    const s = Spine.state;
    const pending = Spine.pending;

    const lvl = s.level || 1;
    const currentXp = s.xp || 0;
    const nextLvlXp = RULES.LEVELS[lvl] || (lvl * 500);
    const prevLvlXp = RULES.LEVELS[lvl - 1] || 0;
    const progressPct = Math.min(100, Math.max(0, Math.round(((currentXp - prevLvlXp) / (nextLvlXp - prevLvlXp || 1)) * 100)));

    el.innerHTML = `
      <div>Level <b>${lvl}</b></div>
      <div class="bar" title="XP: ${currentXp}/${nextLvlXp}"><i style="width: ${progressPct}%"></i></div>
      <div>XP: <b>${currentXp}</b></div>
      <div>🔥 Streak: <b>${s.streak || 0}</b></div>
      ${pending > 0 ? `<div title="Data not yet sent to the server" style="color:var(--brass)">⏳ Pending: <b>${pending}</b></div>` : ''}
    `;
  },

  /**
   * Vẽ thanh điều hướng dưới đáy / trên cùng.
   */
  renderTabbar(currentTab) {
    const el = document.getElementById('tabbar');
    if (!el) return;

    el.innerHTML = NAV.map(item => `
      <a href="${item.href}" ${item.id === currentTab ? 'aria-current="page"' : ''}>
        <span class="ico">${item.ico}</span>
        <span>${item.label}</span>
      </a>
    `).join('');
  },

  /**
   * Cổng nhập mã định danh học sinh (§7).
   */
  renderAuthGate({ module, unit, tab }) {
    if (authGateRendered) return;
    authGateRendered = true;

    const main = document.getElementById('main');
    if (!main) return;

    // Bố cục hai cột: cột trái bảng hiệu, cột phải ô nhập mã.
    // KHÔNG đổi sang email/mật khẩu: trang tĩnh, không có máy chủ xác thực, và
    // mục 3-4 buộc danh tính phải là mã giả danh trên phiếu giấy.
    document.body.classList.add('auth-screen');

    main.innerHTML = `
      <div class="auth-split">

        <section class="auth-hero">
          <span class="auth-wm" aria-hidden="true">10</span>
          <div class="auth-brand">
            <span class="auth-mark"><svg viewBox="0 0 32 32" width="100%" height="100%" aria-hidden="true"><rect width="32" height="32" rx="6" fill="#283567"/><text x="16" y="22" font-size="18" font-family="system-ui, sans-serif" font-weight="bold" text-anchor="middle" fill="#FBFAF7">E</text><circle cx="24" cy="8" r="3" fill="#8A6A1C"/></svg></span>
            <span class="auth-brand-txt">
              <strong>English Insiders Learning Portal</strong>
              <small>English 10 — National Curriculum 2018</small>
            </span>
          </div>

          <!-- Mục 6: nguyên văn, ngay dưới tên dự án, không rút gọn, không ẩn. -->
          <p class="auth-ai" lang="en">
            🤖 All study materials are generated by AI and may contain inaccuracies.
            Please verify critical information independently.
          </p>

          <div class="auth-hero-main">
            <h1 class="auth-h1">Welcome back!<br>Let’s keep learning.</h1>
            <ul class="auth-feats">
              <li><span class="auth-fi" aria-hidden="true">🔥</span>
                <span>Keep your daily streak, XP and level</span></li>
              <li><span class="auth-fi" aria-hidden="true">📚</span>
                <span>Vocabulary · grammar · listening · reading · writing, National Curriculum 2018</span></li>
              <li><span class="auth-fi" aria-hidden="true">🤖</span>
                <span>AI Error Log — practise spotting what AI got wrong, and saying so</span></li>
            </ul>
          </div>
        </section>

        <section class="auth-panel">
          <div class="auth-card">
            <div class="auth-brand auth-brand--sm">
              <span class="auth-mark"><svg viewBox="0 0 32 32" width="100%" height="100%" aria-hidden="true"><rect width="32" height="32" rx="6" fill="#283567"/><text x="16" y="22" font-size="18" font-family="system-ui, sans-serif" font-weight="bold" text-anchor="middle" fill="#FBFAF7">E</text><circle cx="24" cy="8" r="3" fill="#8A6A1C"/></svg></span>
              <span class="auth-brand-txt">
                <strong>English Insiders</strong>
                <small>Learning Portal</small>
              </span>
            </div>

            <h2 class="auth-h2">Sign in</h2>
            <p class="auth-sub">Enter the code on the slip you were given to carry on learning and keep your progress.</p>

            <form id="auth-form" onsubmit="return false;">
              <div class="auth-row">
                <label class="auth-label" for="auth-code-input">Student code</label>
                <span class="auth-lost">Lost your slip? Ask your teacher.</span>
              </div>
              <input
                type="text"
                id="auth-code-input"
                class="auth-input"
                placeholder="NK1009-07"
                inputmode="text"
                autocapitalize="characters"
                autocomplete="off"
                spellcheck="false"
                required
              />
              <div id="auth-error-msg" class="auth-err" style="display:none;"></div>

              <p class="auth-hint">
                Format: <strong>NK</strong> + <strong>class</strong> + hyphen +
                your <strong>register number</strong>.
              </p>

              <button type="submit" id="auth-submit-btn" class="btn btn-wide" disabled>Sign in →</button>
            </form>

            <p class="auth-note">
              This code is not your name. Your teacher uses it only to follow your own
              study progress.<br>
              <em>This device may forget the code if it goes unused for a long time, so keep
              your slip.</em>
            </p>
          </div>
        </section>

      </div>
    `;

    const input = document.getElementById('auth-code-input');
    const btn = document.getElementById('auth-submit-btn');
    const errMsg = document.getElementById('auth-error-msg');
    const form = document.getElementById('auth-form');

    input.addEventListener('input', () => {
      const val = input.value.trim().toUpperCase();
      input.value = val;
      const chk = Identity.validate(val);
      if (chk.ok) {
        btn.disabled = false;
        errMsg.style.display = 'none';
      } else {
        btn.disabled = true;
        if (val.length >= 6) {
          errMsg.textContent = chk.error;
          errMsg.style.display = 'block';
        } else {
          errMsg.style.display = 'none';
        }
      }
    });

    form.addEventListener('submit', async (e) => {
      e.preventDefault();
      const code = input.value.trim().toUpperCase();
      btn.disabled = true;
      btn.textContent = 'Checking…';

      const res = await Spine.signIn(code);
      if (res.ok) {
        location.reload();
      } else {
        btn.disabled = false;
        btn.textContent = 'Sign in';
        errMsg.textContent = res.error || 'That code is not valid. Please check your slip.';
        errMsg.style.display = 'block';
      }
    });
  },

  /**
   * Hiển thị thông báo nhỏ tự ẩn sau 1800ms.
   */
  toast(text) {
    const existing = document.querySelector('.toast');
    if (existing) existing.remove();

    const t = document.createElement('div');
    t.className = 'toast';
    t.textContent = text;
    document.body.appendChild(t);

    setTimeout(() => {
      t.style.transition = 'opacity 0.3s ease';
      t.style.opacity = '0';
      setTimeout(() => t.remove(), 300);
    }, 1800);
  },

  crumb(text, href) {
    return `<a class="crumb" href="${href}">← ${text}</a>`;
  },

  empty(text, href = '/practice/', label = 'Back to Practice →') {
    return `
      <div class="empty-state">
        <p>${text}</p>
        <a class="btn ghost" href="${href}">${label}</a>
      </div>
    `;
  },
};
