// Data Store for English Collocations & Idioms (Gamified Module)

const TRANG_ANH_TOPICS = [
  { id: "all", name: "Tất cả chủ đề (All Topics)", icon: "🔥", count: 160, level: "Mixed" },
  { id: "family", name: "Family & Family Life", icon: "👨‍👩‍👧‍👦", count: 32, level: "B1-C1" },
  { id: "relationships", name: "Relationships & Dating", icon: "❤️", count: 28, level: "B1-C1" },
  { id: "character", name: "Personality & Character", icon: "🧠", count: 28, level: "B1-C2" },
  { id: "everyday_collocations", name: "Essential Collocations", icon: "🎯", count: 27, level: "B1-B2" },
  { id: "color_idioms", name: "Color Idioms", icon: "🎨", count: 14, level: "B2-C1" },
  { id: "body_idioms", name: "Body Part & Animal Idioms", icon: "👀", count: 26, level: "B2-C2" },
  { id: "environment", name: "Environment & Global Issues", icon: "🌍", count: 13, level: "B2-C1" },
  { id: "success_failure", name: "Success, Failure & Cause", icon: "🏆", count: 12, level: "C1-C2" }
];

const TRANG_ANH_COLLOCATIONS = [
  // --- FAMILY & FAMILY LIFE ---
  { id: "ta_f1", phrase: "Immediate family / Nuclear family", meaning: "Gia đình ruột thịt (bố mẹ và con cái)", topic: "family", type: "Family Collocation", example: "I live with my immediate family in Hanoi.", ipa: "/ɪˈmiːdiət ˈfæməli/" },
  { id: "ta_f2", phrase: "Extended family", meaning: "Đại gia đình (ông bà, cô chú, bác, anh em họ...)", topic: "family", type: "Family Collocation", example: "During Tet holiday, our extended family gathers at my grandparents' house.", ipa: "/ɪkˈstendɪd ˈfæməli/" },
  { id: "ta_f3", phrase: "Loving family / Close-knit family", meaning: "Gia đình yêu thương, gắn bó khăng khít", topic: "family", type: "Family Collocation", example: "She grew up in a very close-knit family.", ipa: "/kloʊs nɪt ˈfæməli/" },
  { id: "ta_f4", phrase: "Dysfunctional family", meaning: "Gia đình bất hòa, không êm ấm", topic: "family", type: "Family Collocation", example: "Children from dysfunctional families often need extra counseling.", ipa: "/dɪsˈfʌŋkʃənl ˈfæməli/" },
  { id: "ta_f5", phrase: "Carefree childhood", meaning: "Tuổi thơ vô tư, không phải lo nghĩ", topic: "family", type: "Family Collocation", example: "He enjoyed a carefree childhood in the countryside.", ipa: "/ˈkerfriː ˈtʃaɪldhʊd/" },
  { id: "ta_f6", phrase: "Bitter divorce / Messy divorce", meaning: "Vụ ly hôn cay đắng / đầy tranh chấp tài sản", topic: "family", type: "Family Collocation", example: "They went through a bitter divorce after ten years of marriage.", ipa: "/ˈbɪtər dɪˈvɔːrs/" },
  { id: "ta_f7", phrase: "Broken home", meaning: "Gia đình tan vỡ (bố mẹ ly hôn)", topic: "family", type: "Family Collocation", example: "Many troubled teens come from broken homes.", ipa: "/ˈbroʊkən hoʊm/" },
  { id: "ta_f8", phrase: "Single mother / Single parent", meaning: "Mẹ đơn thân / Bố mẹ đơn thân", topic: "family", type: "Family Collocation", example: "She raised three kids as a single mother.", ipa: "/ˈsɪŋɡl ˈmʌðər/" },
  { id: "ta_f9", phrase: "Family reunion", meaning: "Cuộc đoàn tụ, họp mặt gia đình", topic: "family", type: "Family Collocation", example: "We hold an annual family reunion every summer.", ipa: "/ˈfæməli ˌriːˈjuːniən/" },
  { id: "ta_f10", phrase: "Award sole custody", meaning: "Trao quyền nuôi con duy nhất cho bố hoặc mẹ", topic: "family", type: "Family Collocation", example: "The judge awarded sole custody to the mother.", ipa: "/əˈwɔːrd soʊl ˈkʌstədi/" },
  { id: "ta_f11", phrase: "Pay child support", meaning: "Trợ cấp tiền nuôi con sau ly hôn", topic: "family", type: "Family Collocation", example: "He pays monthly child support to help with schooling expenses.", ipa: "/peɪ tʃaɪld səˈpɔːrt/" },
  { id: "ta_f12", phrase: "Be on good terms with somebody", meaning: "Mối quan hệ hòa nhã, tốt đẹp với ai", topic: "family", type: "Family Collocation", example: "I remain on good terms with all my former colleagues.", ipa: "/bi ɑːn ɡʊd tɜːrmz wɪð/" },
  { id: "ta_f13", phrase: "Give the baby up for adoption", meaning: "Đem con cho người khác nhận nuôi", topic: "family", type: "Family Collocation", example: "The teenage mother decided to give the baby up for adoption.", ipa: "/ɡɪv ðə ˈbeɪbi ʌp fɔːr əˈdɑːpʃn/" },
  { id: "ta_f14", phrase: "Adoptive parents / Birth mother", meaning: "Bố mẹ nuôi / Mẹ ruột", topic: "family", type: "Family Collocation", example: "He loves his adoptive parents deeply while keeping in touch with his birth mother.", ipa: "/əˈdɑːptɪv ˈperənts/" },
  { id: "ta_f15", phrase: "Raise the child / Bring up the child", meaning: "Nuôi nấng, nuôi dạy con cái", topic: "family", type: "Family Collocation", example: "Grandparents helped raise the child while both parents worked full-time.", ipa: "/reɪz ðə tʃaɪld/" },
  { id: "ta_f16", phrase: "Join hands", meaning: "Chung tay, cùng nhau hợp lực", topic: "family", type: "Family Life Collocation", example: "The whole family joined hands to clean up the backyard.", ipa: "/dʒɔɪn hændz/" },
  { id: "ta_f17", phrase: "Give somebody a hand with something", meaning: "Giúp đỡ ai một tay trong việc gì", topic: "family", type: "Family Life Collocation", example: "Can you give me a hand with doing the washing-up?", ipa: "/ɡɪv ˈsʌmbədi ə hænd/" },
  { id: "ta_f18", phrase: "Take responsibility for something", meaning: "Chịu trách nhiệm về điều gì", topic: "family", type: "Family Life Collocation", example: "Each member should take responsibility for household duties.", ipa: "/teɪk rɪˌspɑːnsəˈbɪləti fɔːr/" },
  { id: "ta_f19", phrase: "Be in a hurry", meaning: "Đang vội vã, gấp giáp", topic: "family", type: "Family Life Collocation", example: "Don't leave your room messy just because you are in a hurry.", ipa: "/bi ɪn ə ˈhɜːri/" },
  { id: "ta_f20", phrase: "Try one's best / Do one's best", meaning: "Cố gắng hết sức mình", topic: "family", type: "Family Life Collocation", example: "I will do my best to pass the college entrance examination.", ipa: "/duː wʌnz best/" },
  { id: "ta_f21", phrase: "Be under pressure", meaning: "Chịu áp lực nặng nề", topic: "family", type: "Family Life Collocation", example: "Students often feel under pressure before final exams.", ipa: "/bi ˈʌndər ˈpreʃər/" },
  { id: "ta_f22", phrase: "Men build the house and women make it home", meaning: "Đàn ông xây nhà, đàn bà xây tổ ấm", topic: "family", type: "Proverb Collocation", example: "The old saying goes: Men build the house and women make it home.", ipa: "/men bɪld ðə haʊs/" },
  { id: "ta_f23", phrase: "Split / Divide household chores", meaning: "Phân chia công việc nhà", topic: "family", type: "Family Life Collocation", example: "My parents split household chores equally every day.", ipa: "/splɪt ˈhaʊshoʊld tʃɔːrz/" },
  { id: "ta_f24", phrase: "Heavy lifting", meaning: "Công việc nặng nhọc (bưng bê, vác đồ)", topic: "family", type: "Family Life Collocation", example: "Dad usually handles the heavy lifting in our family.", ipa: "/ˈhevi ˈlɪftɪŋ/" },
  { id: "ta_f25", phrase: "Do the laundry", meaning: "Giặt giũ quần áo", topic: "family", type: "Family Life Collocation", example: "I do the laundry every Saturday morning.", ipa: "/duː ðə ˈlɔːndri/" },
  { id: "ta_f26", phrase: "Do the washing-up", meaning: "Rửa chén bát", topic: "family", type: "Family Life Collocation", example: "Who is going to do the washing-up after dinner?", ipa: "/duː ðə ˈwɑːʃɪŋ ʌp/" },
  { id: "ta_f27", phrase: "Shop for groceries", meaning: "Đi mua thực phẩm, hàng tạp hóa", topic: "family", type: "Family Life Collocation", example: "Mom shops for groceries at the local supermarket twice a week.", ipa: "/ʃɑːp fɔːr ˈɡroʊsəriz/" },
  { id: "ta_f28", phrase: "Breadwinner", meaning: "Trụ cột gia đình (người kiếm tiền chính)", topic: "family", type: "Family Life Collocation", example: "His father is the main breadwinner of the household.", ipa: "/ˈbredwɪnər/" },
  { id: "ta_f29", phrase: "Homemaker", meaning: "Người nội trợ", topic: "family", type: "Family Life Collocation", example: "She chose to be a full-time homemaker to care for her children.", ipa: "/ˈhoʊmmeɪkər/" },
  { id: "ta_f30", phrase: "Set a good example for somebody", meaning: "Nêu gương tốt cho ai noi theo", topic: "family", type: "Family Life Collocation", example: "Older siblings should set a good example for younger ones.", ipa: "/set ə ɡʊd ɪɡˈzæmpl/" },
  { id: "ta_f31", phrase: "Take turns in doing something", meaning: "Thay phiên nhau làm việc gì", topic: "family", type: "Family Life Collocation", example: "We take turns in doing the dishes every evening.", ipa: "/teɪk tɜːrnz ɪn ˈduːɪŋ/" },
  { id: "ta_f32", phrase: "East or West, home is best", meaning: "Không đâu bằng nhà mình (Dù đi đâu cũng không bằng quê nhà)", topic: "family", type: "Proverb Collocation", example: "After travelling all over the world, I still feel east or west, home is best.", ipa: "/iːst ɔːr west hoʊm ɪz best/" },

  // --- RELATIONSHIPS & DATING ---
  { id: "ta_r1", phrase: "Make friends with somebody", meaning: "Kết bạn với ai", topic: "relationships", type: "Relationship Collocation", example: "It's easy to make friends with classmates during orientation week.", ipa: "/meɪk frendz wɪð/" },
  { id: "ta_r2", phrase: "Casual acquaintance", meaning: "Người quen xã giao (chưa thân thiết)", topic: "relationships", type: "Relationship Collocation", example: "He is not a close friend, just a casual acquaintance.", ipa: "/ˈkæʒuəl əˈkweɪntəns/" },
  { id: "ta_r3", phrase: "Love at first sight", meaning: "Tình yêu từ cái nhìn đầu tiên (ái tình sét đánh)", topic: "relationships", type: "Relationship Collocation", example: "For Romeo and Juliet, it was love at first sight.", ipa: "/lʌv æt fɜːrst saɪt/" },
  { id: "ta_r4", phrase: "Fall in love with somebody", meaning: "Phải lòng, đem lòng yêu ai", topic: "relationships", type: "Relationship Collocation", example: "They fell in love with each other during college.", ipa: "/fɔːl ɪn lʌv wɪð/" },
  { id: "ta_r5", phrase: "Significant other", meaning: "Nửa kia, người yêu / bạn đời", topic: "relationships", type: "Relationship Collocation", example: "You are welcome to bring your significant other to the party.", ipa: "/sɪɡˈnɪfɪkənt ˈʌðər/" },
  { id: "ta_r6", phrase: "Soulmate", meaning: "Bạn tri kỷ, người hiểu mình thấu đáo", topic: "relationships", type: "Relationship Collocation", example: "She feels lucky to have found her soulmate.", ipa: "/ˈsoʊlmeɪt/" },
  { id: "ta_r7", phrase: "Match made in heaven", meaning: "Cặp đôi trời sinh, duyên nợ an an", topic: "relationships", type: "Relationship Collocation", example: "They are a match made in heaven, sharing the same passions.", ipa: "/mætʃ meɪd ɪn ˈhevn/" },
  { id: "ta_r8", phrase: "Unrequited love", meaning: "Tình yêu đơn phương (chưa được đáp lại)", topic: "relationships", type: "Relationship Collocation", example: "Unrequited love can be painful and lonely.", ipa: "/ˌʌnrɪˈkwaɪtɪd lʌv/" },
  { id: "ta_r9", phrase: "Childhood sweetheart", meaning: "Tình đầu thời thơ ấu", topic: "relationships", type: "Relationship Collocation", example: "He married his childhood sweetheart after ten years of dating.", ipa: "/ˈtʃaɪldhʊd ˈswiːthɑːrt/" },
  { id: "ta_r10", phrase: "Cheat on somebody", meaning: "Cắm sừng, phản bội người yêu/vợ chồng", topic: "relationships", type: "Relationship Collocation", example: "She broke up with him after discovering he cheated on her.", ipa: "/tʃiːt ɑːn ˈsʌmbədi/" },
  { id: "ta_r11", phrase: "Have something in common", meaning: "Có điểm chung, sở thích tương đồng", topic: "relationships", type: "Relationship Collocation", example: "We get along well because we have so much in common.", ipa: "/hæv ˈsʌmθɪŋ ɪn ˈkɑːmən/" },
  { id: "ta_r12", phrase: "On-off relationship", meaning: "Mối quan hệ lúc tan lúc hợp", topic: "relationships", type: "Relationship Collocation", example: "They had an on-off relationship for three years before finally getting married.", ipa: "/ɑːn ɔːf rɪˈleɪʃnʃɪp/" },
  { id: "ta_r13", phrase: "Hit on someone", meaning: "Tán tỉnh, gạ gẫm ai", topic: "relationships", type: "Relationship Collocation", example: "A guy tried to hit on her at the coffee shop.", ipa: "/hɪt ɑːn ˈsʌmwʌn/" },
  { id: "ta_r14", phrase: "Ask someone out", meaning: "Mời ai đó đi hẹn hò", topic: "relationships", type: "Relationship Collocation", example: "He finally gathered the courage to ask her out for dinner.", ipa: "/æsk ˈsʌmwʌn aʊt/" },
  { id: "ta_r15", phrase: "Hit it off with someone", meaning: "Tâm đầu ý hợp ngay từ lần đầu gặp", topic: "relationships", type: "Relationship Collocation", example: "We hit it off immediately and talked all night.", ipa: "/hɪt ɪt ɔːf wɪð/" },
  { id: "ta_r16", phrase: "Split up / Break up", meaning: "Chia tay, chấm dứt mối quan hệ", topic: "relationships", type: "Relationship Collocation", example: "After months of arguing, they decided to split up.", ipa: "/splɪt ʌp/" },
  { id: "ta_r17", phrase: "Drift apart", meaning: "Từ từ xa cách, không còn thân thiết", topic: "relationships", type: "Relationship Collocation", example: "As they grew older, the two best friends drifted apart.", ipa: "/drɪft əˈpɑːrt/" },
  { id: "ta_r18", phrase: "Head over heels in love", meaning: "Yêu ai tha thiết, say đắm quên lối về", topic: "relationships", type: "Relationship Collocation", example: "Jack is head over heels in love with his new girlfriend.", ipa: "/hed ˈoʊvər hiːlz ɪn lʌv/" },
  { id: "ta_r19", phrase: "Have a crush on someone", meaning: "Thầm thích, thầm thương ai", topic: "relationships", type: "Relationship Collocation", example: "She has had a massive crush on him since high school.", ipa: "/hæv ə krʌʃ ɑːn/" },
  { id: "ta_r20", phrase: "Pop the question", meaning: "Cầu hôn (hỏi cưới ai đó)", topic: "relationships", type: "Relationship Collocation", example: "He popped the question during their romantic trip to Paris.", ipa: "/pɑːp ðə ˈkwestʃən/" },
  { id: "ta_r21", phrase: "Tie the knot / Walk down the aisle", meaning: "Kết hôn, về chung một nhà", topic: "relationships", type: "Relationship Collocation", example: "The happy couple plans to tie the knot next spring.", ipa: "/taɪ ðə nɑːt/" },
  { id: "ta_r22", phrase: "On the rocks", meaning: "Gặp trục trặc, nguy cơ đổ vỡ (mối quan hệ)", topic: "relationships", type: "Relationship Collocation", example: "Their marriage has been on the rocks for months.", ipa: "/ɑːn ðə rɑːks/" },
  { id: "ta_r23", phrase: "Kiss and make up", meaning: "Gương vỡ lại lành, làm hòa sau khi cãi nhau", topic: "relationships", type: "Relationship Collocation", example: "They fight often, but they always kiss and make up quickly.", ipa: "/kɪs ænd meɪk ʌp/" },
  { id: "ta_r24", phrase: "Puppy love", meaning: "Tình yêu bọ xít, mối tình ngây ngô tuổi học trò", topic: "relationships", type: "Relationship Collocation", example: "Don't take it too seriously; it's just puppy love.", ipa: "/ˈpʌpi lʌv/" },
  { id: "ta_r25", phrase: "Platonic relationship", meaning: "Mối quan hệ bạn bè thuần khiết (không có tình yêu)", topic: "relationships", type: "Relationship Collocation", example: "They maintained a purely platonic relationship for years.", ipa: "/pləˈtɑːnɪk rɪˈleɪʃnʃɪp/" },
  { id: "ta_r26", phrase: "Blind date", meaning: "Cuộc gặp mặt gián tiếp (hẹn hò qua giới thiệu)", topic: "relationships", type: "Relationship Collocation", example: "Her friend set her up on a blind date last night.", ipa: "/blaɪnd deɪt/" },
  { id: "ta_r27", phrase: "Heart-to-heart talk", meaning: "Cuộc nói chuyện chân thành, trải lòng", topic: "relationships", type: "Relationship Collocation", example: "We had a long heart-to-heart talk to solve our misunderstandings.", ipa: "/hɑːrt tuː hɑːrt tɔːk/" },
  { id: "ta_r28", phrase: "The apple of one's eye", meaning: "Báu vật, cục cưng trong mắt ai", topic: "relationships", type: "Relationship Collocation", example: "His youngest daughter is the apple of his eye.", ipa: "/ði ˈæpl əv wʌnz aɪ/" },

  // --- PERSONALITY & CHARACTER ---
  { id: "ta_ch1", phrase: "A man of few words", meaning: "Người ít nói, trầm tính", topic: "character", type: "Character Collocation", example: "My grandfather is a man of few words, but when he speaks, everyone listens.", ipa: "/ə mæn əv fjuː wɜːrdz/" },
  { id: "ta_ch2", phrase: "Keep a secret", meaning: "Giữ bí mật", topic: "character", type: "Character Collocation", example: "You can trust her completely; she knows how to keep a secret.", ipa: "/kiːp ə ˈsiːkrət/" },
  { id: "ta_ch3", phrase: "Bear a grudge against somebody", meaning: "Nuôi mối hận, để bụng thù oán ai", topic: "character", type: "Character Collocation", example: "Life is too short to bear a grudge against your old friends.", ipa: "/ber ə ɡrʌdʒ əˈɡenst/" },
  { id: "ta_ch4", phrase: "Brutally honest", meaning: "Thành thật đến mức thô ráp, nói thẳng ruột ngựa", topic: "character", type: "Character Collocation", example: "She gave me a brutally honest opinion about my novel draft.", ipa: "/ˈbruːtəli ˈɑːnɪst/" },
  { id: "ta_ch5", phrase: "Hurt one's feelings", meaning: "Làm tổn thương tình cảm của ai", topic: "character", type: "Character Collocation", example: "I didn't mean to hurt your feelings with my harsh comments.", ipa: "/hɜːrt wʌnz ˈfiːlɪŋz/" },
  { id: "ta_ch6", phrase: "Stubborn streak", meaning: "Tính nết bướng bỉnh, ngang ngạnh", topic: "character", type: "Character Collocation", example: "He has a stubborn streak that makes it hard for him to compromise.", ipa: "/ˈstʌbərn striːk/" },
  { id: "ta_ch7", phrase: "Sharp wit / Sharp-witted", meaning: "Đầu óc nhanh nhạy, thông minh sắc sảo", topic: "character", type: "Character Collocation", example: "Her sharp wit entertained everyone at the dinner table.", ipa: "/ʃɑːrp wɪt/" },
  { id: "ta_ch8", phrase: "Downright rude", meaning: "Cực kỳ vô lễ, hỗn hống", topic: "character", type: "Character Collocation", example: "It was downright rude of him to interrupt the speaker.", ipa: "/ˈdaʊnraɪt ruːd/" },
  { id: "ta_ch9", phrase: "Look one's age / Act one's age", meaning: "Trông đúng tuổi / Cư xử đúng độ tuổi", topic: "character", type: "Character Collocation", example: "Stop throwing tantrums and start acting your age!", ipa: "/ækt wʌnz eɪdʒ/" },
  { id: "ta_ch10", phrase: "Burst with energy", meaning: "Tràn đầy năng lượng, sức sống dồi dào", topic: "character", type: "Character Collocation", example: "The young children were bursting with energy on the playground.", ipa: "/bɜːrst wɪð ˈenərdʒi/" },
  { id: "ta_ch11", phrase: "Sense of humour", meaning: "Tính hài hước, khiếu hài hước", topic: "character", type: "Character Collocation", example: "A good sense of humour helps defuse tense situations.", ipa: "/sens əv ˈhjuːmər/" },
  { id: "ta_ch12", phrase: "Sense of responsibility", meaning: "Tinh thần trách nhiệm cao", topic: "character", type: "Character Collocation", example: "He showed a strong sense of responsibility throughout the project.", ipa: "/sens əv rɪˌspɑːnsəˈbɪləti/" },
  { id: "ta_ch13", phrase: "Selfish streak", meaning: "Nét tính cách ích kỷ", topic: "character", type: "Character Collocation", example: "Beneath his generous persona lies a slight selfish streak.", ipa: "/ˈselfɪʃ striːk/" },
  { id: "ta_ch14", phrase: "Vivid imagination", meaning: "Trí tưởng tượng phong phú, bay bổng", topic: "character", type: "Character Collocation", example: "Fantasy writers need a vivid imagination to build rich worlds.", ipa: "/ˈvɪvɪd ɪˌmædʒɪˈneɪʃn/" },
  { id: "ta_ch15", phrase: "Keep one's temper / Lose one's temper", meaning: "Giữ bình tĩnh / Mất bình tĩnh, nổi giận", topic: "character", type: "Character Collocation", example: "It's important to keep your temper even under severe provocation.", ipa: "/kiːp wʌnz ˈtempər/" },
  { id: "ta_ch16", phrase: "Fiercely loyal", meaning: "Cực kỳ trung thành, một lòng một dạ", topic: "character", type: "Character Collocation", example: "Dogs are fiercely loyal companions to their owners.", ipa: "/ˈfɪrsli ˈlɔɪəl/" },
  { id: "ta_ch17", phrase: "Put others first", meaning: "Đặt lợi ích người khác lên trên bản thân", topic: "character", type: "Character Collocation", example: "A selfless person always puts others first.", ipa: "/pʊt ˈʌðərz fɜːrst/" },
  { id: "ta_ch18", phrase: "Painfully shy", meaning: "Cực kỳ nhút nhát, e ấp", topic: "character", type: "Character Collocation", example: "As a child, she was painfully shy and avoided eye contact.", ipa: "/ˈpeɪnfəli ʃaɪ/" },
  { id: "ta_ch19", phrase: "Supremely confident", meaning: "Cực kỳ tự tin vào bản thân", topic: "character", type: "Character Collocation", example: "He stepped onto the stage looking supremely confident.", ipa: "/suːˈpriːmli ˈkɑːnfɪdənt/" },
  { id: "ta_ch20", phrase: "Come out of one's shell", meaning: "Trở nên cởi mở, tự tin hơn (thoát khỏi vỏ bọc)", topic: "character", type: "Character Collocation", example: "Joining the drama club helped him come out of his shell.", ipa: "/kʌm aʊt əv wʌnz ʃel/" },
  { id: "ta_ch21", phrase: "Speak one's mind", meaning: "Thẳng thắn bộc bạch quan điểm", topic: "character", type: "Character Collocation", example: "Don't be afraid to speak your mind during the staff meeting.", ipa: "/spiːk wʌnz maɪnd/" },
  { id: "ta_ch22", phrase: "Bite one's tongue", meaning: "Nhẫn nhịn, kiềm chế không phát ngôn", topic: "character", type: "Character Collocation", example: "I wanted to argue back, but I decided to bite my tongue.", ipa: "/baɪt wʌnz tʌŋ/" },
  { id: "ta_ch23", phrase: "Show true colors", meaning: "Bộc lộ bản chất thật", topic: "character", type: "Character Collocation", example: "Under intense pressure, he finally showed his true colors.", ipa: "/ʃoʊ truː ˈkʌlərz/" },
  { id: "ta_ch24", phrase: "As good as gold", meaning: "Hiền lành, ngoan ngoãn như vàng", topic: "character", type: "Character Collocation", example: "The children were as good as gold while guests were over.", ipa: "/æz ɡʊd æz ɡoʊld/" },
  { id: "ta_ch25", phrase: "As stubborn as a mule", meaning: "Bướng bỉnh như lừa, không lay chuyển", topic: "character", type: "Character Collocation", example: "Good luck convincing him; he's as stubborn as a mule.", ipa: "/æz ˈstʌbərn æz ə mjuːl/" },
  { id: "ta_ch26", phrase: "As hard as nails", meaning: "Cứng rắn, lạnh lùng tàn nhẫn", topic: "character", type: "Character Collocation", example: "The prosecutor was as hard as nails in court.", ipa: "/æz hɑːrd æz neɪlz/" },
  { id: "ta_ch27", phrase: "As pleased as punch", meaning: "Vui mừng khôn xiết, cực kỳ hài lòng", topic: "character", type: "Character Collocation", example: "She was as pleased as punch with her exam score.", ipa: "/æz pliːzd æz pʌntʃ/" },
  { id: "ta_ch28", phrase: "As keen as mustard", meaning: "Hăng hái, nhiệt tình sôi nổi", topic: "character", type: "Character Collocation", example: "The new intern is as keen as mustard to learn everything.", ipa: "/æz kiːn æz ˈmʌstərd/" },

  // --- ESSENTIAL COLLOCATIONS ---
  { id: "ta_e1", phrase: "Let one's hair down", meaning: "Thư giãn, xả hơi thoải mái", topic: "everyday_collocations", type: "Essential Collocation", example: "It's Friday night! Time to let your hair down.", ipa: "/let wʌnz her daʊn/" },
  { id: "ta_e2", phrase: "Drop-dead gorgeous", meaning: "Tuyệt đẹp, đẹp mê hồn", topic: "everyday_collocations", type: "Essential Collocation", example: "She looked drop-dead gorgeous in her evening gown.", ipa: "/drɑːp ded ˈɡɔːrdʒəs/" },
  { id: "ta_e3", phrase: "Make headlines", meaning: "Trở thành tin tức giật gân, lên trang nhất báo chí", topic: "everyday_collocations", type: "Essential Collocation", example: "The scientific discovery made headlines around the world.", ipa: "/meɪk ˈhedlaɪnz/" },
  { id: "ta_e4", phrase: "Take measures to do something", meaning: "Thực hiện các biện pháp để giải quyết điều gì", topic: "everyday_collocations", type: "Essential Collocation", example: "The government must take measures to curb air pollution.", ipa: "/teɪk ˈmeʒərz tuː duː/" },
  { id: "ta_e5", phrase: "Pave the way for something", meaning: "Mở đường, tạo tiền đề thuận lợi cho cái gì", topic: "everyday_collocations", type: "Essential Collocation", example: "His research paved the way for new medical treatments.", ipa: "/peɪv ðə weɪ fɔːr/" },
  { id: "ta_e6", phrase: "Speak highly of somebody/something", meaning: "Đánh giá rất cao, khen ngợi hết lời", topic: "everyday_collocations", type: "Essential Collocation", example: "All his former professors speak highly of him.", ipa: "/spiːk ˈhaɪli əv/" },
  { id: "ta_e7", phrase: "Get straight to the point", meaning: "Đi thẳng vào vấn đề, không vòng vo", topic: "everyday_collocations", type: "Essential Collocation", example: "Let's get straight to the point: what is your budget?", ipa: "/ɡet streɪt tuː ðə pɔɪnt/" },
  { id: "ta_e8", phrase: "Make ends meet", meaning: "Xoay xở đủ sống, kiếm đủ tiền trang trải", topic: "everyday_collocations", type: "Essential Collocation", example: "They have to work two jobs just to make ends meet.", ipa: "/meɪk endz miːt/" },
  { id: "ta_e9", phrase: "Take it for granted", meaning: "Cho điều gì là hiển nhiên, không biết trân trọng", topic: "everyday_collocations", type: "Essential Collocation", example: "Don't take your health for granted.", ipa: "/teɪk ɪt fɔːr ˈɡræntɪd/" },
  { id: "ta_e10", phrase: "Make up one's mind", meaning: "Quyết định, đưa ra lựa chọn", topic: "everyday_collocations", type: "Essential Collocation", example: "I can't make up my mind between the blue car and the red one.", ipa: "/meɪk ʌp wʌnz maɪnd/" },
  { id: "ta_e11", phrase: "Pay attention to something", meaning: "Chú ý, lắng nghe cẩn thận", topic: "everyday_collocations", type: "Essential Collocation", example: "Please pay attention to the safety instructions.", ipa: "/peɪ əˈtenʃn tuː/" },
  { id: "ta_e12", phrase: "Keep / Catch up with somebody", meaning: "Theo kịp, bắt kịp trình độ của ai", topic: "everyday_collocations", type: "Essential Collocation", example: "He worked extra hours to catch up with his peers.", ipa: "/kætʃ ʌp wɪð/" },
  { id: "ta_e13", phrase: "Put a stop to something", meaning: "Chấm dứt, ngăn chặn điều gì", topic: "everyday_collocations", type: "Essential Collocation", example: "Authorities must put a stop to illegal logging.", ipa: "/pʊt ə stɑːp tuː/" },
  { id: "ta_e14", phrase: "Break new ground", meaning: "Khám phá ra điều mới mẻ, khai phá lối đi riêng", topic: "everyday_collocations", type: "Essential Collocation", example: "Her pioneering research broke new ground in genetics.", ipa: "/breɪk njuː ɡraʊnd/" },
  { id: "ta_e15", phrase: "Be rushed off one's feet", meaning: "Bận rộn túi bụi, chạy đôn chạy đáo", topic: "everyday_collocations", type: "Essential Collocation", example: "Waiters were rushed off their feet during lunchtime.", ipa: "/bi rʌʃt ɔːf wʌnz fiːt/" },
  { id: "ta_e16", phrase: "Come under fire", meaning: "Bị chỉ trích dữ dội", topic: "everyday_collocations", type: "Essential Collocation", example: "The minister came under fire for his controversial policy.", ipa: "/kʌm ˈʌndər ˈfaɪər/" },
  { id: "ta_e17", phrase: "Get a kick out of something", meaning: "Thích thú, tìm thấy niềm vui lớn từ cái gì", topic: "everyday_collocations", type: "Essential Collocation", example: "He gets a kick out of riding motorbikes fast.", ipa: "/ɡet ə kɪk aʊt əv/" },
  { id: "ta_e18", phrase: "Kick up a fuss", meaning: "Làm ầm ĩ, phản đối kịch liệt", topic: "everyday_collocations", type: "Essential Collocation", example: "The customer kicked up a fuss about the slow service.", ipa: "/kɪk ʌp ə fʌs/" },
  { id: "ta_e19", phrase: "Out of the question", meaning: "Không thể xảy ra, không đời nào chấp nhận", topic: "everyday_collocations", type: "Essential Collocation", example: "Buying a luxury yacht is completely out of the question.", ipa: "/aʊt əv ðə ˈkwestʃən/" },
  { id: "ta_e20", phrase: "Out of date / Out of order", meaning: "Hết hạn / Bị hỏng hóc", topic: "everyday_collocations", type: "Essential Collocation", example: "The elevator is temporarily out of order.", ipa: "/aʊt əv ˈoːrdər/" },
  { id: "ta_e21", phrase: "Rise to the occasion", meaning: "Tỏ ra có khả năng đối phó với tình thế khó khăn", topic: "everyday_collocations", type: "Essential Collocation", example: "The young goalkeeper rose to the occasion during penalty shootout.", ipa: "/raɪz tuː ðə əˈkeɪʒn/" },
  { id: "ta_e22", phrase: "Cross one's mind", meaning: "Chợt nảy ra trong trí óc", topic: "everyday_collocations", type: "Essential Collocation", example: "It never crossed my mind that he would betray us.", ipa: "/krɔːs wʌnz maɪnd/" },
  { id: "ta_e23", phrase: "Make a fortune", meaning: "Kiếm được một tài sản kếch xù", topic: "everyday_collocations", type: "Essential Collocation", example: "He made a fortune investing in real estate early on.", ipa: "/meɪk ə ˈfɔːrtʃuːn/" },
  { id: "ta_e24", phrase: "Come down with something", meaning: "Bị mắc bệnh gì (cảm cúm, sốt)", topic: "everyday_collocations", type: "Essential Collocation", example: "I think I'm coming down with the flu.", ipa: "/kʌm daʊn wɪð/" },
  { id: "ta_e25", phrase: "Make up for something", meaning: "Bù đắp cho điều gì", topic: "everyday_collocations", type: "Essential Collocation", example: "He bought her flowers to make up for being late.", ipa: "/meɪk ʌp fɔːr/" },
  { id: "ta_e26", phrase: "Put up with something", meaning: "Chịu đựng điều gì gây khó chịu", topic: "everyday_collocations", type: "Essential Collocation", example: "I can no longer put up with his loud music at midnight.", ipa: "/pʊt ʌp wɪð/" },
  { id: "ta_e27", phrase: "Commit something to memory", meaning: "Ghi nhớ chính xác điều gì", topic: "everyday_collocations", type: "Essential Collocation", example: "Actors must commit their entire script to memory.", ipa: "/kəˈmɪt ˈsʌmθɪŋ tuː ˈmeməri/" },

  // --- COLOR IDIOMS ---
  { id: "ta_c1", phrase: "Out of the blue", meaning: "Hoàn toàn bất ngờ, đột ngột không báo trước", topic: "color_idioms", type: "Color Idiom", example: "One day, out of the blue, she called me from Paris.", ipa: "/aʊt əv ðə bluː/" },
  { id: "ta_c2", phrase: "Once in a blue moon", meaning: "Hiếm khi, năm thì mười họa mới xảy ra", topic: "color_idioms", type: "Color Idiom", example: "He visits his hometown once in a blue moon.", ipa: "/wʌns ɪn ə bluː muːn/" },
  { id: "ta_c3", phrase: "Paint the town red", meaning: "Đi chơi đêm, quẩy tưng bừng ăn mừng", topic: "color_idioms", type: "Color Idiom", example: "After passing the bar exam, they went out to paint the town red.", ipa: "/peɪnt ðə taʊn red/" },
  { id: "ta_c4", phrase: "Catch somebody red-handed", meaning: "Bắt quả tang ai đang làm điều sai trái", topic: "color_idioms", type: "Color Idiom", example: "The thief was caught red-handed trying to steal a laptop.", ipa: "/kætʃ red ˈhændɪd/" },
  { id: "ta_c5", phrase: "The black sheep of the family", meaning: "Đứa con ngỗ ngược, làm xấu mặt gia đình", topic: "color_idioms", type: "Color Idiom", example: "Jack was considered the black sheep because he refused to study law.", ipa: "/ðə blæk ʃiːp/" },
  { id: "ta_c6", phrase: "Red-letter day", meaning: "Ngày đáng nhớ, ngày đại hỷ/vui mừng", topic: "color_idioms", type: "Color Idiom", example: "Graduation day was a red-letter day for our entire family.", ipa: "/red ˈletər deɪ/" },
  { id: "ta_c7", phrase: "In the pink", meaning: "Sức khỏe cực kỳ tốt, dồi dào năng lượng", topic: "color_idioms", type: "Color Idiom", example: "My grandfather is 80 years old but still in the pink.", ipa: "/ɪn ðə pɪŋk/" },
  { id: "ta_c8", phrase: "With flying colors", meaning: "Thành công rực rỡ, đạt điểm số xuất sắc", topic: "color_idioms", type: "Color Idiom", example: "She passed her IELTS exam with flying colors.", ipa: "/wɪð ˈflaɪɪŋ ˈkʌlərz/" },
  { id: "ta_c9", phrase: "Blue in the face", meaning: "Nói đến rạc cổ, nói mãi mà không có tác dụng", topic: "color_idioms", type: "Color Idiom", example: "You can argue until you're blue in the face, but I won't change my mind.", ipa: "/bluː ɪn ðə feɪs/" },
  { id: "ta_c10", phrase: "White as a ghost / sheet", meaning: "Trắng bệch, nhợt nhạt vì sợ hãi", topic: "color_idioms", type: "Color Idiom", example: "When he heard the loud noise, he turned as white as a ghost.", ipa: "/waɪt æz ə ɡoʊst/" },
  { id: "ta_c11", phrase: "In black and white", meaning: "Rõ ràng bằng giấy trắng mực đen", topic: "color_idioms", type: "Color Idiom", example: "I want the contract terms written down in black and white.", ipa: "/ɪn blæk ænd waɪt/" },
  { id: "ta_c12", phrase: "Have a yellow streak", meaning: "Có tính nhát gan, thiếu dũng khí", topic: "color_idioms", type: "Color Idiom", example: "He refused to go into the dark cave because he has a yellow streak.", ipa: "/hæv ə ˈjeloʊ striːk/" },
  { id: "ta_c13", phrase: "Get / Give the green light", meaning: "Được bật đèn xanh, cho phép thực hiện", topic: "color_idioms", type: "Color Idiom", example: "The city council gave the green light for building the new park.", ipa: "/ɡet ðə ɡriːn laɪt/" },
  { id: "ta_c14", phrase: "Red tape", meaning: "Nạn quan liêu, thủ tục hành chính rườm rà", topic: "color_idioms", type: "Color Idiom", example: "Starting a small business involves navigating through a lot of red tape.", ipa: "/red teɪp/" },

  // --- BODY PART & ANIMAL IDIOMS ---
  { id: "ta_b1", phrase: "Break a leg", meaning: "Chúc may mắn (trước giờ diễn/thi/phỏng vấn)", topic: "body_idioms", type: "Body Idiom", example: "Break a leg at your presentation today!", ipa: "/breɪk ə leɡ/" },
  { id: "ta_b2", phrase: "Cost an arm and a leg", meaning: "Rất đắt đỏ, tốn kém cả gia tài", topic: "body_idioms", type: "Body Idiom", example: "That designer handbag cost an arm and a leg.", ipa: "/kɔːst ən ɑːrm ænd ə leɡ/" },
  { id: "ta_b3", phrase: "Hit the nail on the head", meaning: "Nói đúng trọng tâm, chuẩn xác 100%", topic: "body_idioms", type: "Body Idiom", example: "You hit the nail on the head with that market analysis.", ipa: "/hɪt ðə neɪl ɑːn ðə hed/" },
  { id: "ta_b4", phrase: "Pay through the nose", meaning: "Trả giá quá đắt cho cái gì", topic: "body_idioms", type: "Body Idiom", example: "We had to pay through the nose for last-minute flight tickets.", ipa: "/peɪ θruː ðə noʊz/" },
  { id: "ta_b5", phrase: "By the skin of one's teeth", meaning: "Sát sao, vừa vặn trong tấc lụa", topic: "body_idioms", type: "Body Idiom", example: "He passed the test by the skin of his teeth.", ipa: "/baɪ ðə skɪn əv wʌnz tiːθ/" },
  { id: "ta_b6", phrase: "Pull someone's leg", meaning: "Trêu chọc, giỡn mặt với ai", topic: "body_idioms", type: "Body Idiom", example: "Don't worry, I'm just pulling your leg!", ipa: "/pʊl ˈsʌmwʌnz leɡ/" },
  { id: "ta_b7", phrase: "See eye to eye with somebody", meaning: "Hoàn toàn đồng tình, nhất trí quan điểm với ai", topic: "body_idioms", type: "Body Idiom", example: "My boss and I don't always see eye to eye on advertising.", ipa: "/siː aɪ tuː aɪ wɪð/" },
  { id: "ta_b8", phrase: "Keep an eye on somebody/something", meaning: "Mắt để ý, trông chừng ai/cái gì", topic: "body_idioms", type: "Body Idiom", example: "Please keep an eye on my luggage while I buy a coffee.", ipa: "/kiːp ən aɪ ɑːn/" },
  { id: "ta_b9", phrase: "A splitting headache", meaning: "Cơn đau đầu như búa bổ", topic: "body_idioms", type: "Body Idiom", example: "I had a splitting headache after staring at the screen all day.", ipa: "/ə ˈsplɪtɪŋ ˈhedeɪk/" },
  { id: "ta_b10", phrase: "Make one's blood boil", meaning: "Làm ai sôi máu, tức giận điên người", topic: "body_idioms", type: "Body Idiom", example: "Cruelty to animals makes my blood boil.", ipa: "/meɪk wʌnz blʌd bɔɪl/" },
  { id: "ta_b11", phrase: "Not bat an eye", meaning: "Không mảy may giật mình, thản nhiên trước nguy khó", topic: "body_idioms", type: "Body Idiom", example: "He didn't bat an eye when told the bad news.", ipa: "/nɑːt bæt ən aɪ/" },
  { id: "ta_b12", phrase: "Get / Have cold feet", meaning: "Mất hết can đảm, chùn bước phút chót", topic: "body_idioms", type: "Body Idiom", example: "The groom got cold feet right before the ceremony.", ipa: "/ɡet koʊld fiːt/" },
  { id: "ta_b13", phrase: "Put one's foot in it", meaning: "Lỡ lời làm tổn thương/gây lúng túng cho ai", topic: "body_idioms", type: "Body Idiom", example: "I really put my foot in it when I asked about her ex-husband.", ipa: "/pʊt wʌnz fʊt ɪn ɪt/" },
  { id: "ta_b14", phrase: "Like the back of one's hand", meaning: "Rõ như lòng bàn tay", topic: "body_idioms", type: "Body Idiom", example: "He has lived here for 30 years and knows the city like the back of his hand.", ipa: "/laɪk ðə bæk əv wʌnz hænd/" },
  { id: "ta_b15", phrase: "In the twinkling of an eye", meaning: "Trong nháy mắt, cực kỳ nhanh chóng", topic: "body_idioms", type: "Body Idiom", example: "The thief disappeared in the twinkling of an eye.", ipa: "/ɪn ðə ˈtwɪŋklɪŋ əv ən aɪ/" },
  { id: "ta_b16", phrase: "On the tip of one's tongue", meaning: "Đang trên đầu lưỡi (sắp nhớ ra nhưng chưa thốt ra được)", topic: "body_idioms", type: "Body Idiom", example: "Her name is on the tip of my tongue, but I can't recall it right now.", ipa: "/ɑːn ðə tɪp əv wʌnz tʌŋ/" },
  { id: "ta_b17", phrase: "A real pain in the neck", meaning: "Mối phiền phức, điều gây bực mình lớn", topic: "body_idioms", type: "Body Idiom", example: "Filing all these receipts manually is a real pain in the neck.", ipa: "/ə rɪəl peɪn ɪn ðə nek/" },
  { id: "ta_b18", phrase: "Keep one's head above water", meaning: "Xoay xở tồn tại, vượt qua khó khăn tài chính", topic: "body_idioms", type: "Body Idiom", example: "With rising inflation, small businesses struggle to keep their heads above water.", ipa: "/kiːp wʌnz hed əˈbʌv ˈwɔːtər/" },
  { id: "ta_b19", phrase: "Have egg on one's face", meaning: "Bị ngượng mặt, xấu hổ vì mắc lỗi ngớ ngẩn", topic: "body_idioms", type: "Body Idiom", example: "The company had egg on its face after the false product release statement.", ipa: "/hæv eɡ ɑːn wʌnz feɪs/" },
  { id: "ta_b20", phrase: "Lend an ear to somebody", meaning: "Chân thành lắng nghe ai tâm sự", topic: "body_idioms", type: "Body Idiom", example: "A true friend is always ready to lend a sympathetic ear.", ipa: "/lend ən ɪr tuː/" },
  { id: "ta_b21", phrase: "Up to one's eyes / neck in work", meaning: "Bận ngập đầu ngập cổ trong công việc", topic: "body_idioms", type: "Body Idiom", example: "I can't go out tonight; I'm up to my eyes in paperwork.", ipa: "/ʌp tuː wʌnz aɪz/" },
  { id: "ta_b22", phrase: "A sweet tooth", meaning: "Người thèm đồ ngọt, khoái ăn bánh kẹo", topic: "body_idioms", type: "Body Idiom", example: "She has a real sweet tooth and eats chocolate after every meal.", ipa: "/ə swiːt tuːθ/" },
  { id: "ta_b23", phrase: "Take the mickey out of somebody", meaning: "Chế nhạo, giễu cợt trêu chọc ai", topic: "body_idioms", type: "Animal Idiom", example: "His classmates used to take the mickey out of his thick glasses.", ipa: "/teɪk ðə ˈmɪki aʊt əv/" },
  { id: "ta_b24", phrase: "Get butterflies in one's stomach", meaning: "Cảm thấy bồn chồn, hồi hộp trước sự kiện lớn", topic: "body_idioms", type: "Animal Idiom", example: "I always get butterflies in my stomach before going on stage.", ipa: "/ɡet ˈbʌtərflaɪz ɪn wʌnz ˈstʌmək/" },
  { id: "ta_b25", phrase: "When pigs fly", meaning: "Chuyện không đời nào xảy ra (hoang đường)", topic: "body_idioms", type: "Animal Idiom", example: "He will clean his room when pigs fly!", ipa: "/wen pɪɡz flaɪ/" },
  { id: "ta_b26", phrase: "Let the cat out of the bag", meaning: "Tiết lộ bí mật vô tình hay cố ý", topic: "body_idioms", type: "Animal Idiom", example: "Who let the cat out of the bag about the surprise party?", ipa: "/let ðə kæt aʊt əv ðə bæɡ/" },

  // --- ENVIRONMENT & GLOBAL ISSUES ---
  { id: "ta_env1", phrase: "Disturb / Upset the ecological balance", meaning: "Làm mất cân bằng sinh thái", topic: "environment", type: "Environment Collocation", example: "Chemical dumping will upset the ecological balance of the lake.", ipa: "/ʌpˈset ðə ˌiːkəˈlɑːdʒɪkl ˈbæləns/" },
  { id: "ta_env2", phrase: "Deplete the ozone layer", meaning: "Làm suy giảm / thủng tầng ozon", topic: "environment", type: "Environment Collocation", example: "Harmful CFC gases deplete the ozone layer.", ipa: "/dɪˈpliːt ðə ˈoʊzoʊn ˈleɪər/" },
  { id: "ta_env3", phrase: "Suffer the consequences", meaning: "Gánh chịu hậu quả nặng nề", topic: "environment", type: "Environment Collocation", example: "If we ignore global warming, future generations will suffer the consequences.", ipa: "/ˈsʌfər ðə ˈkɑːnsəkwensɪz/" },
  { id: "ta_env4", phrase: "Environmentally friendly", meaning: "Thân thiện với môi trường", topic: "environment", type: "Environment Collocation", example: "Solar energy is an environmentally friendly power source.", ipa: "/ɪnˌvaɪrənˈmentəli ˈfrendli/" },
  { id: "ta_env5", phrase: "Fossil fuels", meaning: "Nhiên liệu hóa thạch (than đá, dầu mỏ)", topic: "environment", type: "Environment Collocation", example: "Burning fossil fuels releases massive amounts of carbon dioxide.", ipa: "/ˈfɑːsl ˈfjuːəl z/" },
  { id: "ta_env6", phrase: "Greenhouse gases", meaning: "Khí nhà kính", topic: "environment", type: "Environment Collocation", example: "Emissions of greenhouse gases contribute directly to global warming.", ipa: "/ˈɡriːnhaʊs ˈɡæsɪz/" },
  { id: "ta_env7", phrase: "Rising sea levels", meaning: "Mực nước biển dâng cao", topic: "environment", type: "Environment Collocation", example: "Coastal cities face flooding due to rising sea levels.", ipa: "/ˈraɪzɪŋ siː ˈlevlz/" },
  { id: "ta_env8", phrase: "Live below the poverty line", meaning: "Sống dưới mức chuẩn nghèo", topic: "environment", type: "Social Issue Collocation", example: "Millions of families in remote areas live below the poverty line.", ipa: "/lɪv bɪˈloʊ ðə ˈpɑːvərti laɪn/" },
  { id: "ta_env9", phrase: "Alleviate poverty", meaning: "Xóa đói giảm nghèo, cải thiện đời sống", topic: "environment", type: "Social Issue Collocation", example: "Micro-loans help alleviate poverty in rural communities.", ipa: "/əˈliːvieɪt ˈpɑːvərti/" },
  { id: "ta_env10", phrase: "Exhaust fumes", meaning: "Khí thải từ phương tiện giao thông", topic: "environment", type: "Environment Collocation", example: "Exhaust fumes from cars cause severe smog in major cities.", ipa: "/ɪɡˈzɔːst fjuːmz/" },
  { id: "ta_env11", phrase: "Crop failure", meaning: "Mất mùa, thất thu vụ mùa", topic: "environment", type: "Environment Collocation", example: "Severe drought led to widespread crop failure across the province.", ipa: "/krɑːp ˈfeɪljər/" },
  { id: "ta_env12", phrase: "Bumper crop", meaning: "Vụ mùa bội thu, trúng lớn", topic: "environment", type: "Agriculture Collocation", example: "Farmers celebrated a bumper crop of rice this autumn.", ipa: "/ˈbʌmpər krɑːp/" },
  { id: "ta_env13", phrase: "On the brink of war", meaning: "Trên bờ vực chiến tranh", topic: "environment", type: "Global Issue Collocation", example: "Tensions between neighboring nations brought them to the brink of war.", ipa: "/ɑːn ðə brɪŋk əv wɔːr/" },

  // --- SUCCESS, FAILURE & CAUSE ---
  { id: "ta_sf1", phrase: "Make a breakthrough", meaning: "Tạo ra bước đột phá quan trọng", topic: "success_failure", type: "Academic Collocation", example: "Scientists made a major breakthrough in cancer research.", ipa: "/meɪk ə ˈbreɪkθruː/" },
  { id: "ta_sf2", phrase: "Crowning achievement", meaning: "Thành tựu cao quý nhất, vẻ vang nhất", topic: "success_failure", type: "Academic Collocation", example: "Winning the Nobel Prize was the crowning achievement of her career.", ipa: "/ˈkraʊnɪŋ əˈtʃiːvmənt/" },
  { id: "ta_sf3", phrase: "Fail miserably", meaning: "Thất bại thảm hại", topic: "success_failure", type: "Academic Collocation", example: "The poorly planned project failed miserably.", ipa: "/feɪl ˈmɪzrəbli/" },
  { id: "ta_sf4", phrase: "A recipe for disaster", meaning: "Mầm mống hiểm họa, chắc chắn dẫn đến thất bại", topic: "success_failure", type: "Academic Collocation", example: "Mixing alcohol and driving is a recipe for disaster.", ipa: "/ə ˈresəpi fɔːr dɪˈzæstər/" },
  { id: "ta_sf5", phrase: "Phenomenal success", meaning: "Thành công ngoạn mục, phi thường", topic: "success_failure", type: "Academic Collocation", example: "The new app enjoyed phenomenal success within weeks.", ipa: "/fəˈnɑːmɪnl səkˈses/" },
  { id: "ta_sf6", phrase: "Dramatic improvement", meaning: "Sự cải thiện đáng kể, vượt bậc", topic: "success_failure", type: "Academic Collocation", example: "There was a dramatic improvement in her test scores.", ipa: "/drəˈmætɪk ɪmˈpruːvmənt/" },
  { id: "ta_sf7", phrase: "Make good progress", meaning: "Tiến bộ nhanh chóng, khả quan", topic: "success_failure", type: "Academic Collocation", example: "The students are making good progress in learning English.", ipa: "/meɪk ɡʊd ˈprɑːɡres/" },
  { id: "ta_sf8", phrase: "Cause damage to something", meaning: "Gây thiệt hại, hư hại nặng nề cho cái gì", topic: "success_failure", type: "Cause & Effect Collocation", example: "The typhoon caused severe damage to coastal infrastructure.", ipa: "/kɔːz ˈdæmɪdʒ tuː/" },
  { id: "ta_sf9", phrase: "Root cause", meaning: "Nguyên nhân sâu xa, cốt lõi của vấn đề", topic: "success_failure", type: "Cause & Effect Collocation", example: "Poverty is often the root cause of high crime rates.", ipa: "/ruːt kɔːz/" },
  { id: "ta_sf10", phrase: "Have a significant impact on", meaning: "Có tác động quan trọng, sâu sắc tới", topic: "success_failure", type: "Cause & Effect Collocation", example: "Social media has a significant impact on teenage mental health.", ipa: "/hæv ə sɪɡˈnɪfɪkənt ˈɪmpækt ɑːn/" },
  { id: "ta_sf11", phrase: "Reach a compromise", meaning: "Đạt được sự thỏa hiệp, thống nhất", topic: "success_failure", type: "Agreement Collocation", example: "After long negotiations, both sides reached a fair compromise.", ipa: "/riːtʃ ə ˈkɑːmprəmaɪz/" },
  { id: "ta_sf12", phrase: "A heated argument", meaning: "Cuộc tranh luận gay gắt, nảy lửa", topic: "success_failure", type: "Agreement Collocation", example: "They got into a heated argument over budget allocations.", ipa: "/ə ˈhiːtɪd ˈɑːrɡjumənt/" }
];

const TRANG_ANH_QUIZ_QUESTIONS = [
  {
    id: "ta_q1",
    topic: "family",
    question: "The technological advances ______ birth to the Industrial Revolution, transforming modern manufacturing.",
    options: ["A. took", "B. gave", "C. had", "D. made"],
    correct: 1,
    explanation: "Cụm từ cố định 'give birth to something' mang nghĩa khai sinh, sinh ra, làm xuất hiện điều gì.",
    explanationEn: "'Give birth to something' means to cause something to exist or begin."
  },
  {
    id: "ta_q2",
    topic: "family",
    question: "A number of the kids in my classroom come from ______ homes where parents are divorced.",
    options: ["A. broken", "B. damaged", "C. hurt", "D. separated"],
    correct: 0,
    explanation: "Cụm từ 'a broken home' chỉ gia đình tan vỡ, cha mẹ ly hôn.",
    explanationEn: "'A broken home' refers to a family in which the parents have divorced or separated."
  },
  {
    id: "ta_q3",
    topic: "family",
    question: "After a ______ divorce from his wife of 20 years, the actor married a woman young enough to be his daughter.",
    options: ["A. hostile", "B. unhappy", "C. bitter", "D. normal"],
    correct: 2,
    explanation: "Cụm từ 'a bitter divorce' chỉ vụ ly hôn đầy cay đắng, tranh chấp gay gắt.",
    explanationEn: "'A bitter divorce' involves strong feelings of hatred or resentment."
  },
  {
    id: "ta_q4",
    topic: "family",
    question: "In many traditional societies, the husband is considered the sole ______ who earns money for the family.",
    options: ["A. homemaker", "B. breadwinner", "C. housekeeper", "D. babysitter"],
    correct: 1,
    explanation: "Cụm từ 'breadwinner' là người kiếm tiền chính (trụ cột gia đình).",
    explanationEn: "'Breadwinner' is the person who earns money to support a family."
  },
  {
    id: "ta_q5",
    topic: "relationships",
    question: "They have so much ______ common that they can talk for hours without feeling bored.",
    options: ["A. in", "B. at", "C. on", "D. with"],
    correct: 0,
    explanation: "Cụm từ 'have something in common' mang nghĩa có điểm chung.",
    explanationEn: "'Have in common' means sharing interests, experiences, or qualities."
  },
  {
    id: "ta_q6",
    topic: "relationships",
    question: "Jack and Mary hit it ______ immediately when they met at the summer camp.",
    options: ["A. out", "B. off", "C. up", "D. on"],
    correct: 1,
    explanation: "Cụm từ 'hit it off' nghĩa là hợp cạ, tâm đầu ý hợp ngay từ đầu.",
    explanationEn: "'Hit it off' means to quickly become good friends."
  },
  {
    id: "ta_q7",
    topic: "relationships",
    question: "After dating for five years, he decided to ______ the question on Valentine's Day.",
    options: ["A. pop", "B. ask", "C. break", "D. drop"],
    correct: 0,
    explanation: "Cụm thành ngữ 'pop the question' có nghĩa là cầu hôn.",
    explanationEn: "'Pop the question' means to propose marriage to someone."
  },
  {
    id: "ta_q8",
    topic: "character",
    question: "She has a ______ streak and rarely listens to advice from anyone else.",
    options: ["A. stubborn", "B. strict", "C. silent", "D. slow"],
    correct: 0,
    explanation: "Cụm từ 'stubborn streak' chỉ nét tính cách bướng bỉnh, ngang ngạnh.",
    explanationEn: "'Stubborn streak' means a tendency to be stubborn."
  },
  {
    id: "ta_q9",
    topic: "character",
    question: "Don't be so sensitive; he was just ______ your leg when he said you lost the keys.",
    options: ["A. pushing", "B. pulling", "C. shaking", "D. holding"],
    correct: 1,
    explanation: "Cụm từ 'pull someone's leg' nghĩa là trêu chọc, giỡn với ai.",
    explanationEn: "'Pull someone's leg' means to tease or fool someone playfully."
  },
  {
    id: "ta_q10",
    topic: "everyday_collocations",
    question: "It is Friday night! Let your ______ down and enjoy the weekend.",
    options: ["A. head", "B. hair", "C. arms", "D. shoes"],
    correct: 1,
    explanation: "Cụm 'let one's hair down' mang nghĩa thư giãn, xả hơi thoải mái.",
    explanationEn: "'Let one's hair down' means to relax and enjoy oneself."
  },
  {
    id: "ta_q11",
    topic: "everyday_collocations",
    question: "The government must take prompt ______ to prevent further environmental damage.",
    options: ["A. measures", "B. steps", "C. actions", "D. All are correct"],
    correct: 3,
    explanation: "Các cụm 'take measures / take steps / take action' đều mang nghĩa thực hiện biện pháp/hành động giải quyết.",
    explanationEn: "All options mean taking appropriate actions to deal with a problem."
  },
  {
    id: "ta_q12",
    topic: "color_idioms",
    question: "The announcement came completely out of the ______, surprising everyone in the office.",
    options: ["A. red", "B. blue", "C. green", "D. black"],
    correct: 1,
    explanation: "Cụm 'out of the blue' mang nghĩa bất ngờ, không báo trước.",
    explanationEn: "'Out of the blue' means completely unexpectedly."
  },
  {
    id: "ta_q13",
    topic: "color_idioms",
    question: "She passed her final medical exams with ______ colors and earned a scholarship.",
    options: ["A. flying", "B. bright", "C. shining", "D. glowing"],
    correct: 0,
    explanation: "Cụm thành ngữ 'with flying colors' có nghĩa là đạt kết quả rực rỡ, điểm xuất sắc.",
    explanationEn: "'With flying colors' means with very high marks or great success."
  },
  {
    id: "ta_q14",
    topic: "body_idioms",
    question: "Buying that brand new sports car cost him an arm and a ______. ",
    options: ["A. foot", "B. hand", "C. leg", "D. shoulder"],
    correct: 2,
    explanation: "Cụm 'cost an arm and a leg' nghĩa là rất đắt đỏ, tốn kém.",
    explanationEn: "'Cost an arm and a leg' means extremely expensive."
  },
  {
    id: "ta_q15",
    topic: "body_idioms",
    question: "You hit the nail on the ______ when you pointed out the main flaw in our marketing strategy.",
    options: ["A. head", "B. top", "C. point", "D. mind"],
    correct: 0,
    explanation: "Cụm 'hit the nail on the head' nghĩa là nói đúng trọng tâm, chuẩn xác.",
    explanationEn: "'Hit the nail on the head' means to describe exactly what is causing a situation."
  },
  {
    id: "ta_q16",
    topic: "environment",
    question: "Excessive emissions of greenhouse gases directly ______ the ozone layer.",
    options: ["A. damage", "B. deplete", "C. reduce", "D. decay"],
    correct: 1,
    explanation: "Cụm 'deplete the ozone layer' nghĩa là làm suy giảm / thủng tầng ozon.",
    explanationEn: "'Deplete the ozone layer' means reducing the protective ozone layer."
  },
  {
    id: "ta_q17",
    topic: "success_failure",
    question: "Without proper planning, combining these two volatile substances is a ______ for disaster.",
    options: ["A. recipe", "B. formula", "C. key", "D. secret"],
    correct: 0,
    explanation: "Cụm thành ngữ 'a recipe for disaster' nghĩa là mầm mống hiểm họa, chắc chắn gây thất bại.",
    explanationEn: "'A recipe for disaster' means a combination of factors bound to result in danger or failure."
  }
];
