# -*- coding: utf-8 -*-
import json
import re

with open('c:/hsg2627.github.io/scratch/deploy_full_destination_vocab.py', 'r', encoding='utf-8') as f:
    orig_py = f.read()

# Let's extract existing DATA from deploy_full_destination_vocab.py
# Or define clean complete DATA
UNIT26_DATA = [
    {
        "unit": 26,
        "unitTitle": "Unit 26: Preference & Leisure",
        "shop": "Leisure Garden",
        "speaker": "Gamer Tama",
        "avatar": "🎮",
        "verb": "centre around",
        "sentence": "The festival activities primarily <span class='blank'>_______</span> traditional folk games and culinary arts.",
        "hint": "be main subject of attention/interest | xoay quanh ai hay một chủ đề nào đó",
        "meaningEn": "if sth centers around sb or sth, or you center sth around them, they are its main subject of attention or interest",
        "meaningVn": "xoay quanh ai hay một chủ đề nào đó",
        "options": ["centre around", "get into", "go in for", "mess about"],
        "correct": 0,
        "explanation": "Chính xác! 'Centre around' nghĩa là xoay quanh trọng tâm là ai hoặc chủ đề nào đó."
    },
    {
        "unit": 26,
        "unitTitle": "Unit 26: Preference & Leisure",
        "shop": "Leisure Garden",
        "speaker": "Artist Mimi",
        "avatar": "🎨",
        "verb": "get into",
        "sentence": "Recently, she has begun to <span class='blank'>_______</span> classical oil painting and chess.",
        "hint": "start enjoying sth or become enthusiastic about it | bắt đầu hứng thú với điều gì đó",
        "meaningEn": "start enjoying sth or become enthusiastic about it; (train/plane) arrive; become involved in a bad situation",
        "meaningVn": "bắt đầu hứng thú/đam mê điều gì; đến nơi (tàu xe); dính líu vào rắc rối",
        "options": ["get into", "go off", "keep up", "take out"],
        "correct": 0,
        "explanation": "Tuyệt vời! 'Get into' nghĩa là bắt đầu yêu thích say mê một sở thích hay hoạt động mới."
    },
    {
        "unit": 26,
        "unitTitle": "Unit 26: Preference & Leisure",
        "shop": "Leisure Garden",
        "speaker": "Coach Katsu",
        "avatar": "⚽",
        "verb": "go in for",
        "sentence": "My brother doesn't really <span class='blank'>_______</span> extreme sports like bungee jumping.",
        "hint": "enjoy a particular thing/activity or choose as career | thích thú, tham gia hoạt động/nghề nghiệp",
        "meaningEn": "enjoy a particular thing or activity; choose sth as a subject of study or as your career",
        "meaningVn": "thích thú về một chủ đề/hoạt động; chọn điều gì đó làm ngành nghề theo đuổi",
        "options": ["go in for", "seek out", "warm up", "take off"],
        "correct": 0,
        "explanation": "Đúng! 'Go in for' nghĩa là ham mê, có xu hướng tham gia hoặc chọn theo đuổi."
    },
    {
        "unit": 26,
        "unitTitle": "Unit 26: Preference & Leisure",
        "shop": "Leisure Garden",
        "speaker": "Maestro Luna",
        "avatar": "🎭",
        "verb": "go off",
        "sentence": "After eating too much seafood during the trip, I completely <span class='blank'>_______</span> sushi.",
        "hint": "stop liking sb or sth | không còn thích/chán ngấy",
        "meaningEn": "stop liking sb or sth; explode or be fired; leave a place; (food) spoil",
        "meaningVn": "dừng thích ai đó; nổ súng; rời khỏi nơi nào; (thực phẩm) bị hư hỏng, ôi thiu",
        "options": ["go off", "laze around", "put in", "centre around"],
        "correct": 0,
        "explanation": "Chính xác! 'Go off' sb/sth nghĩa là không còn thích, chán ngấy ai hoặc cái gì."
    },
    {
        "unit": 26,
        "unitTitle": "Unit 26: Preference & Leisure",
        "shop": "Leisure Garden",
        "speaker": "Gamer Tama",
        "avatar": "🎮",
        "verb": "grow on",
        "sentence": "I disliked the indie rock album at first, but it is slowly beginning to <span class='blank'>_______</span> me.",
        "hint": "if sth/sb grows on you, you start to like them more | dần dần khiến ai yêu thích",
        "meaningEn": "if sth or sb grows on you, you start to like them more",
        "meaningVn": "ai đó dần dà cảm thấy thích thú/mến mộ cái gì hơn",
        "options": ["grow on", "mess about", "take to", "keep up"],
        "correct": 0,
        "explanation": "Tuyệt vời! 'Grow on' nghĩa là dần dần chiếm được cảm tình, ngày càng thấy thích."
    },
    {
        "unit": 26,
        "unitTitle": "Unit 26: Preference & Leisure",
        "shop": "Leisure Garden",
        "speaker": "Artist Mimi",
        "avatar": "🎨",
        "verb": "hang out",
        "sentence": "During summer weekends, teenagers usually <span class='blank'>_______</span> at the local skatepark.",
        "hint": "spend time in a place or with people | dành thời gian giao lưu, tụ tập đi chơi",
        "meaningEn": "spend time in a particular place or with particular people; lean out of a window",
        "meaningVn": "dành thời gian với ai tại nơi nào đó; rướn người ra cửa sổ",
        "options": ["hang out", "take in", "seek out", "go off"],
        "correct": 0,
        "explanation": "Đúng! 'Hang out' nghĩa là dành thời gian tụ tập la cà cùng bạn bè."
    },
    {
        "unit": 26,
        "unitTitle": "Unit 26: Preference & Leisure",
        "shop": "Leisure Garden",
        "speaker": "Coach Katsu",
        "avatar": "⚽",
        "verb": "keep up",
        "sentence": "He jogged at a brisk pace, so I had to sprint just to <span class='blank'>_______</span> with him.",
        "hint": "continue to do sth or move at same speed | tiếp tục làm việc; chạy đuổi kịp tốc độ",
        "meaningEn": "continue to do sth; move at the same speed as sb or sth",
        "meaningVn": "tiếp tục làm việc gì đó; chạy theo kịp tốc độ của ai",
        "options": ["keep up", "laze around", "take out", "warm up"],
        "correct": 0,
        "explanation": "Chính xác! 'Keep up (with)' là duy trì nhịp độ, theo kịp bước ai đó."
    },
    {
        "unit": 26,
        "unitTitle": "Unit 26: Preference & Leisure",
        "shop": "Leisure Garden",
        "speaker": "Maestro Luna",
        "avatar": "🎭",
        "verb": "laze around",
        "sentence": "On lazy Sunday afternoons, there is nothing better than to <span class='blank'>_______</span> by the poolside.",
        "hint": "relax and enjoy yourself, doing no work | thư giãn và không làm gì cả",
        "meaningEn": "relax and enjoy yourself, doing no work",
        "meaningVn": "thư giãn và không làm gì cả, nghỉ ngơi lười biếng",
        "options": ["laze around", "put in", "centre around", "seek out"],
        "correct": 0,
        "explanation": "Rất tốt! 'Laze around' là thong thả nghỉ ngơi, xả hơi lười biếng."
    },
    {
        "unit": 26,
        "unitTitle": "Unit 26: Preference & Leisure",
        "shop": "Leisure Garden",
        "speaker": "Gamer Tama",
        "avatar": "🎮",
        "verb": "mess about",
        "sentence": "Stop trying to <span class='blank'>_______</span> in the workshop and focus on assembling the model plane!",
        "hint": "spend time doing things in relaxed way or behave silly | dành thời gian làm linh tinh, nghịch ngợm",
        "meaningEn": "spend time doing things in a relaxed way; behave in a silly way",
        "meaningVn": "dành thời gian làm gì thư giãn; cư xử một cách nghịch ngợm ngớ ngẩn",
        "options": ["mess about", "go in for", "take off", "grow on"],
        "correct": 0,
        "explanation": "Đúng! 'Mess about/around' là nghịch ngợm, làm trò bông đùa vô bổ."
    },
    {
        "unit": 26,
        "unitTitle": "Unit 26: Preference & Leisure",
        "shop": "Leisure Garden",
        "speaker": "Artist Mimi",
        "avatar": "🎨",
        "verb": "pick up",
        "sentence": "While living in Tokyo for six months, Leo managed to <span class='blank'>_______</span> conversational Japanese.",
        "hint": "learn skill without intending to or meet sb in vehicle | học lỏm, tiếp thu tự nhiên; đón ai",
        "meaningEn": "learn a new skill or start a habit without intending to; go and meet sb in a vehicle",
        "meaningVn": "bắt đầu học kĩ năng hay sở thích mới cách vô tình; đi đón ai bằng xe",
        "options": ["pick up", "get into", "take in", "keep up"],
        "correct": 0,
        "explanation": "Chính xác! 'Pick up' mang nghĩa học lỏm, tiếp thu kỹ năng một cách tự nhiên."
    },
    {
        "unit": 26,
        "unitTitle": "Unit 26: Preference & Leisure",
        "shop": "Leisure Garden",
        "speaker": "Coach Katsu",
        "avatar": "⚽",
        "verb": "put in",
        "sentence": "To master the violin concerto, she had to <span class='blank'>_______</span> at least four hours of daily practice.",
        "hint": "spend particular time/effort doing sth | dành thời gian hay công sức làm việc gì",
        "meaningEn": "spend a particular amount of time doing sth, or make a particular amount of effort in order to do sth",
        "meaningVn": "dành thời gian hay công sức làm việc gì đó",
        "options": ["put in", "laze around", "go off", "hang out"],
        "correct": 0,
        "explanation": "Chuẩn xác! 'Put in' (time/effort) là cống hiến, đầu tư nhiều thời gian công sức."
    },
    {
        "unit": 26,
        "unitTitle": "Unit 26: Preference & Leisure",
        "shop": "Leisure Garden",
        "speaker": "Maestro Luna",
        "avatar": "🎭",
        "verb": "seek out",
        "sentence": "Passionate antique collectors often travel across provinces to <span class='blank'>_______</span> rare handcrafted pottery.",
        "hint": "find sb/sth by looking in determined way | quyết tâm tìm kiếm ai/cái gì",
        "meaningEn": "find sb or sth by looking for them in a determined way",
        "meaningVn": "quyết tâm tìm kiếm, cất công săn lùng ai/cái gì",
        "options": ["seek out", "centre around", "mess about", "take to"],
        "correct": 0,
        "explanation": "Tuyệt vời! 'Seek out' nghĩa là chủ động cất công tìm kiếm mục tiêu xác định."
    },
    {
        "unit": 26,
        "unitTitle": "Unit 26: Preference & Leisure",
        "shop": "Leisure Garden",
        "speaker": "Gamer Tama",
        "avatar": "🎮",
        "verb": "take in",
        "sentence": "The two-week cultural tour will <span class='blank'>_______</span> visits to ancient temples and scenic mountain trails.",
        "hint": "include sth | bao gồm, bao quát",
        "meaningEn": "include sth",
        "meaningVn": "bao gồm, bao hàm",
        "options": ["take in", "take off", "grow on", "warm up"],
        "correct": 0,
        "explanation": "Đúng! 'Take in' có nghĩa là bao hàm, bao gồm các điểm đến hoặc nội dung."
    },
    {
        "unit": 26,
        "unitTitle": "Unit 26: Preference & Leisure",
        "shop": "Leisure Garden",
        "speaker": "Artist Mimi",
        "avatar": "🎨",
        "verb": "take off",
        "sentence": "The board game club really began to <span class='blank'>_______</span> once they started hosting weekly tournaments.",
        "hint": "have time away from work or become popular fast | có thời gian nghỉ; phất lên nhanh chóng",
        "meaningEn": "have a particular amount of time away from work; become successful or popular very fast",
        "meaningVn": "có thời gian nghỉ ngơi; trở nên thành công và nổi tiếng rất nhanh",
        "options": ["take off", "keep up", "laze around", "go off"],
        "correct": 0,
        "explanation": "Chính xác! 'Take off' nghĩa là cất cánh, bùng nổ độ nổi tiếng và thành công."
    },
    {
        "unit": 26,
        "unitTitle": "Unit 26: Preference & Leisure",
        "shop": "Leisure Garden",
        "speaker": "Coach Katsu",
        "avatar": "⚽",
        "verb": "take out",
        "sentence": "For his birthday celebration, his uncle decided to <span class='blank'>_______</span> him to a fancy steakhouse.",
        "hint": "take sb to cinema/restaurant and pay | dẫn ai đó đến rạp chiếu phim hay nhà hàng và khao tiền",
        "meaningEn": "take sb to a place like a cinema or a restaurant and usually pay for them",
        "meaningVn": "dẫn ai đó đến rạp chiếu phim hay nhà hàng và khao tiền",
        "options": ["take out", "put in", "seek out", "get into"],
        "correct": 0,
        "explanation": "Tuyệt vời! 'Take sb out' là mời, dẫn ai ra ngoài đi chơi/ăn uống và khao."
    },
    {
        "unit": 26,
        "unitTitle": "Unit 26: Preference & Leisure",
        "shop": "Leisure Garden",
        "speaker": "Maestro Luna",
        "avatar": "🎭",
        "verb": "warm up",
        "sentence": "Athletes should always spend fifteen minutes doing light stretches to <span class='blank'>_______</span> before the marathon.",
        "hint": "prepare for sport/activity by gentle exercises | khởi động (trước khi chơi thể thao)",
        "meaningEn": "prepare for a sport or activity by doing gentle exercises or practicing just before it starts",
        "meaningVn": "khởi động (trước khi chơi thể thao), làm nóng cơ thể",
        "options": ["warm up", "take to", "mess about", "grow on"],
        "correct": 0,
        "explanation": "Đúng! 'Warm up' là bài tập làm nóng người, khởi động trước buổi tập."
    },
    {
        "unit": 26,
        "unitTitle": "Unit 26: Preference & Leisure",
        "shop": "Leisure Garden",
        "speaker": "Artist Mimi",
        "avatar": "🎨",
        "verb": "take to",
        "sentence": "She immediately <span class='blank'>_______</span> oil painting as if she had been practicing for years.",
        "hint": "begin to like sb/sth or start habit | bắt đầu thích ai hoặc việc gì; bắt đầu một thói quen",
        "meaningEn": "begin to like sb or sth; start doing sth as a habit",
        "meaningVn": "thích ai hoặc việc gì; bắt đầu một thói quen",
        "options": ["take to", "go off", "hang out", "centre around"],
        "correct": 0,
        "explanation": "Chính xác! 'Take to' nghĩa là bén duyên, bắt đầu có cảm tình hoặc hình thành thói quen mới."
    }
]

print(f"Prepared {len(UNIT26_DATA)} Unit 26 Phrasal Verbs!")
