import json
import os

idioms_data = [
    # UNIT 2: THINKING AND LEARNING (12 idioms)
    {
        "id": 1,
        "unit": 2,
        "unit_title": "Unit 2: Thinking and Learning",
        "guardian": "🦉 Athena Owl of Wisdom",
        "idiom": "go to sb's head",
        "clean_phrase": "go to one's head",
        "meaning_en": "if success goes to sb's head, it makes them think that they are very important and makes them a less pleasant person",
        "meaning_vi": "khiến chúng ta quá đề cao bản thân và trở nên hống hách",
        "example": "Don't let all this sudden fame go to your head; stay humble and keep working hard.",
        "cloze_sentence": "Don't let all this sudden fame _____ your head; stay humble and keep working hard.",
        "cloze_options": ["go to", "come to", "fall into", "turn into"]
    },
    {
        "id": 2,
        "unit": 2,
        "unit_title": "Unit 2: Thinking and Learning",
        "guardian": "🦉 Athena Owl of Wisdom",
        "idiom": "have/keep your wits about you",
        "clean_phrase": "keep your wits about you",
        "meaning_en": "be able to think quickly and make sensible decisions/ being constantly alert",
        "meaning_vi": "có khả năng xử lý và đưa ra những phản hồi nhanh nhẹn/ luôn cảnh giác",
        "example": "In a sudden crisis or emergency, you must always keep your wits about you.",
        "cloze_sentence": "In a sudden crisis or emergency, you must always _____ your wits about you.",
        "cloze_options": ["keep", "hold", "throw", "lose"]
    },
    {
        "id": 3,
        "unit": 2,
        "unit_title": "Unit 2: Thinking and Learning",
        "guardian": "🦉 Athena Owl of Wisdom",
        "idiom": "in the dark (about)",
        "clean_phrase": "in the dark about",
        "meaning_en": "not knowing very much about sth, because other people are keeping it secret from you",
        "meaning_vi": "không biết nhiều về một thứ gì đó, thứ mà được người khác giữ bí mật",
        "example": "The employees were completely kept in the dark about the upcoming corporate merger.",
        "cloze_sentence": "The employees were completely kept in the _____ about the upcoming corporate merger.",
        "cloze_options": ["dark", "shade", "shadow", "fog"]
    },
    {
        "id": 4,
        "unit": 2,
        "unit_title": "Unit 2: Thinking and Learning",
        "guardian": "🦉 Athena Owl of Wisdom",
        "idiom": "know what's what",
        "clean_phrase": "know what's what",
        "meaning_en": "if you know what's what, you have a lot of experience and can judge people and situations well",
        "meaning_vi": "biết rõ về một thứ gì đó",
        "example": "Ask Uncle David for legal advice; he's been in the business for forty years and really knows what's what.",
        "cloze_sentence": "Ask David for advice; he has twenty years of experience and really knows _____.",
        "cloze_options": ["what's what", "which is which", "who's who", "where's where"]
    },
    {
        "id": 5,
        "unit": 2,
        "unit_title": "Unit 2: Thinking and Learning",
        "guardian": "🦉 Athena Owl of Wisdom",
        "idiom": "not have a leg to stand on",
        "clean_phrase": "not have a leg to stand on",
        "meaning_en": "not have any way of proving that you are right about sth",
        "meaning_vi": "không có luận cứ để chứng minh bản thân đúng ở một việc gì đó",
        "example": "Without tangible evidence or signed receipts, you don't have a leg to stand on in court.",
        "cloze_sentence": "Without any physical evidence, the prosecutor didn't have a _____ to stand on.",
        "cloze_options": ["leg", "foot", "base", "ground"]
    },
    {
        "id": 6,
        "unit": 2,
        "unit_title": "Unit 2: Thinking and Learning",
        "guardian": "🦉 Athena Owl of Wisdom",
        "idiom": "not see the wood for the trees",
        "clean_phrase": "not see the wood for the trees",
        "meaning_en": "be unable to get a general understanding of a situation because you are too worried about the details",
        "meaning_vi": "không thể nhìn nhận ra tổng thể vấn đề vì quá để ý vào những chi tiết lặt vặt",
        "example": "He was obsessing over tiny formatting errors and failed to see the wood for the trees.",
        "cloze_sentence": "He was obsessing over tiny errors and couldn't see the _____ for the trees.",
        "cloze_options": ["wood", "forest", "leaves", "branches"]
    },
    {
        "id": 7,
        "unit": 2,
        "unit_title": "Unit 2: Thinking and Learning",
        "guardian": "🦉 Athena Owl of Wisdom",
        "idiom": "put two and two together",
        "clean_phrase": "put two and two together",
        "meaning_en": "guess the truth about a situation from what you have seen or heard",
        "meaning_vi": "suy ra một điều gì đó từ một việc mình được thấy hoặc nghe",
        "example": "Seeing them arriving in the same car, I quickly put two and two together and guessed they were dating.",
        "cloze_sentence": "Seeing them holding hands, she put _____ together and realized they were a couple.",
        "cloze_options": ["two and two", "one and one", "heads", "facts"]
    },
    {
        "id": 8,
        "unit": 2,
        "unit_title": "Unit 2: Thinking and Learning",
        "guardian": "🦉 Athena Owl of Wisdom",
        "idiom": "quick/slow on the uptake",
        "clean_phrase": "quick/slow on the uptake",
        "meaning_en": "taking a very short/long time to understand or realize sth",
        "meaning_vi": "nhanh/chậm trong việc tiếp thu một vấn đề nào đó",
        "example": "He's exceptionally quick on the uptake, mastering advanced calculus within a few lessons.",
        "cloze_sentence": "She understood the complex instructions immediately because she is so quick on the _____.",
        "cloze_options": ["uptake", "takeoff", "insight", "intake"]
    },
    {
        "id": 9,
        "unit": 2,
        "unit_title": "Unit 2: Thinking and Learning",
        "guardian": "🦉 Athena Owl of Wisdom",
        "idiom": "ring a bell (with sb)",
        "clean_phrase": "ring a bell",
        "meaning_en": "sound familiar",
        "meaning_vi": "gợi lên cảm giác quen thuộc",
        "example": "His name rings a bell, but I cannot recall where we first met.",
        "cloze_sentence": "Does the name Professor Sterling _____ a bell with you?",
        "cloze_options": ["ring", "strike", "sound", "toll"]
    },
    {
        "id": 10,
        "unit": 2,
        "unit_title": "Unit 2: Thinking and Learning",
        "guardian": "🦉 Athena Owl of Wisdom",
        "idiom": "round/around the bend",
        "clean_phrase": "round the bend",
        "meaning_en": "be/become mentally confused or unable to act in a reasonable way",
        "meaning_vi": "trở nên mất kiểm soát / phát điên",
        "example": "The constant drilling noise from the construction site is driving me round the bend!",
        "cloze_sentence": "The non-stop loud music is driving all the neighbors _____ the bend.",
        "cloze_options": ["round", "over", "across", "along"]
    },
    {
        "id": 11,
        "unit": 2,
        "unit_title": "Unit 2: Thinking and Learning",
        "guardian": "🦉 Athena Owl of Wisdom",
        "idiom": "split hairs",
        "clean_phrase": "split hairs",
        "meaning_en": "argue about small details of sth",
        "meaning_vi": "cãi vã về những vấn đề nhỏ nhặt",
        "example": "Whether we arrive at 7:02 or 7:05 is just splitting hairs; we are on time!",
        "cloze_sentence": "Stop splitting _____ over minor details and let's focus on the big picture.",
        "cloze_options": ["hairs", "threads", "straws", "atoms"]
    },
    {
        "id": 12,
        "unit": 2,
        "unit_title": "Unit 2: Thinking and Learning",
        "guardian": "🦉 Athena Owl of Wisdom",
        "idiom": "take stock (of)",
        "clean_phrase": "take stock of",
        "meaning_en": "spend some time thinking about the situation you are in before you decide what to do next",
        "meaning_vi": "dành thời gian suy nghĩ/ đắn đo một việc gì đó của bản thân trước khi quyết định sẽ làm gì tiếp theo",
        "example": "After a grueling semester, it was time to rest and take stock of our academic progress.",
        "cloze_sentence": "Before launching a new campaign, the director paused to take _____ of the current market.",
        "cloze_options": ["stock", "care", "count", "note"]
    },

    # UNIT 4: CHANGE AND TECHNOLOGY (10 idioms)
    {
        "id": 13,
        "unit": 4,
        "unit_title": "Unit 4: Change and Technology",
        "guardian": "⚡ Cyber Phoenix of Innovation",
        "idiom": "a leopard can't change its spots",
        "clean_phrase": "a leopard can't change its spots",
        "meaning_en": "used for saying that sb will never change their behavior or character",
        "meaning_vi": "ý nói không thể thay đổi bản chất của một người",
        "example": "He promised he would stop lying, but a leopard can't change its spots.",
        "cloze_sentence": "He returned to his old deceitful habits; a leopard can't change its _____.",
        "cloze_options": ["spots", "stripes", "skin", "claws"]
    },
    {
        "id": 14,
        "unit": 4,
        "unit_title": "Unit 4: Change and Technology",
        "guardian": "⚡ Cyber Phoenix of Innovation",
        "idiom": "all mod cons",
        "clean_phrase": "all mod cons",
        "meaning_en": "all modern conveniences, the machines and devices, such as washing machines and fridges, which make the ordinary jobs in a home easier",
        "meaning_vi": "những công nghệ hiện đại khiến công việc trong cuộc sống thường ngày dễ dàng hơn (tủ lạnh, máy rửa chén,...)",
        "example": "The luxury penthouse is fully furnished and equipped with all mod cons.",
        "cloze_sentence": "Their newly renovated smart apartment comes fitted with all _____ cons.",
        "cloze_options": ["mod", "tech", "smart", "pro"]
    },
    {
        "id": 15,
        "unit": 4,
        "unit_title": "Unit 4: Change and Technology",
        "guardian": "⚡ Cyber Phoenix of Innovation",
        "idiom": "break the mould",
        "clean_phrase": "break the mould",
        "meaning_en": "change a situation by doing sth that is very different from what most people usually do or have done in the past",
        "meaning_vi": "thay đổi tình thế bằng việc thực hiện một điều mới lạ so với tiêu chuẩn trước đây",
        "example": "Her revolutionary design broke the mould of traditional eco-friendly architecture.",
        "cloze_sentence": "His unorthodox teaching approach completely broke the _____ of traditional education.",
        "cloze_options": ["mould", "glass", "frame", "cycle"]
    },
    {
        "id": 16,
        "unit": 4,
        "unit_title": "Unit 4: Change and Technology",
        "guardian": "⚡ Cyber Phoenix of Innovation",
        "idiom": "change your tune",
        "clean_phrase": "change your tune",
        "meaning_en": "change your opinion or attitude",
        "meaning_vi": "thay đổi thái độ và ý kiến",
        "example": "He used to criticize electric vehicles, but he changed his tune after test-driving one.",
        "cloze_sentence": "Once he saw how profitable the venture was, he quickly changed his _____.",
        "cloze_options": ["tune", "song", "voice", "melody"]
    },
    {
        "id": 17,
        "unit": 4,
        "unit_title": "Unit 4: Change and Technology",
        "guardian": "⚡ Cyber Phoenix of Innovation",
        "idiom": "have a change of heart",
        "clean_phrase": "have a change of heart",
        "meaning_en": "change your opinion about sth or decide not to do sth you were planning to do",
        "meaning_vi": "thay đổi quan điểm về một việc gì đó và dừng lại việc đang làm",
        "example": "She had planned to resign, but had a change of heart after being offered a promotion.",
        "cloze_sentence": "The CEO had a change of _____ and decided not to cancel the AI scholarship program.",
        "cloze_options": ["heart", "mind", "mood", "soul"]
    },
    {
        "id": 18,
        "unit": 4,
        "unit_title": "Unit 4: Change and Technology",
        "guardian": "⚡ Cyber Phoenix of Innovation",
        "idiom": "know sth inside out",
        "clean_phrase": "know sth inside out",
        "meaning_en": "know everything about a subject",
        "meaning_vi": "biết \"tất tần tật\" về những thứ liên quan đến một thứ gì đó",
        "example": "As the lead software architect, she knows the entire codebase inside out.",
        "cloze_sentence": "He has been coding for ten years and knows the operating system inside _____.",
        "cloze_options": ["out", "in", "up", "through"]
    },
    {
        "id": 19,
        "unit": 4,
        "unit_title": "Unit 4: Change and Technology",
        "guardian": "⚡ Cyber Phoenix of Innovation",
        "idiom": "reinvent the wheel",
        "clean_phrase": "reinvent the wheel",
        "meaning_en": "waste time trying to create sth that sb else has already created",
        "meaning_vi": "lãng phí thời gian tạo dựng một thứ gì đó mà người khác đã làm trước đây",
        "example": "We don't need to reinvent the wheel; just import the standard open-source library.",
        "cloze_sentence": "There's no point in trying to reinvent the _____ when established methods work perfectly.",
        "cloze_options": ["wheel", "engine", "gear", "circle"]
    },
    {
        "id": 20,
        "unit": 4,
        "unit_title": "Unit 4: Change and Technology",
        "guardian": "⚡ Cyber Phoenix of Innovation",
        "idiom": "stick to sb's guns (on sth)",
        "clean_phrase": "stick to one's guns",
        "meaning_en": "refuse to change what you are saying or doing despite the opposition or criticism of other people",
        "meaning_vi": "giữ vững lập trường mặc cho sự chỉ trích và chống đối",
        "example": "Despite severe backlash from the board, the inventor stuck to his guns regarding data privacy.",
        "cloze_sentence": "Despite immense public pressure, the senator stuck to his _____.",
        "cloze_options": ["guns", "swords", "shields", "arms"]
    },
    {
        "id": 21,
        "unit": 4,
        "unit_title": "Unit 4: Change and Technology",
        "guardian": "⚡ Cyber Phoenix of Innovation",
        "idiom": "the tools of the trade",
        "clean_phrase": "tools of the trade",
        "meaning_en": "the skills and equipment that you need in order to do your job",
        "meaning_vi": "kỹ năng cần thiết cho một công việc",
        "example": "A high-end drawing tablet and stylus are essential tools of the trade for digital illustrators.",
        "cloze_sentence": "A fast computer and debugger software are the vital tools of the _____ for programmers.",
        "cloze_options": ["trade", "craft", "job", "work"]
    },
    {
        "id": 22,
        "unit": 4,
        "unit_title": "Unit 4: Change and Technology",
        "guardian": "⚡ Cyber Phoenix of Innovation",
        "idiom": "turn over a new leaf",
        "clean_phrase": "turn over a new leaf",
        "meaning_en": "change your life by starting to be a better person or stopping a bad habit",
        "meaning_vi": "thay đổi cuộc sống sang một chương mới bằng cách trở thành một người tốt hơn",
        "example": "After his recovery, he turned over a new leaf and dedicated his time to charity.",
        "cloze_sentence": "Starting this New Year, she decided to turn over a new _____ and exercise daily.",
        "cloze_options": ["leaf", "page", "chapter", "book"]
    },

    # UNIT 6: TIME AND WORK (12 idioms)
    {
        "id": 23,
        "unit": 6,
        "unit_title": "Unit 6: Time and Work",
        "guardian": "⏳ Chrono Sphinx of Timeless Realms",
        "idiom": "a stitch in time (saves nine)",
        "clean_phrase": "a stitch in time saves nine",
        "meaning_en": "used for saying that it is better to solve a problem now, rather than leave it until later when it may be more difficult to deal with",
        "meaning_vi": "được sử dụng để nói rằng mình nên ngay lập tức làm một việc gì đó trước khi để nó trở nên khó khăn hơn trong tương lai",
        "example": "Fix the leaking pipe today; remember that a stitch in time saves nine!",
        "cloze_sentence": "Patch up the small roof leak now; remember, a _____ in time saves nine.",
        "cloze_options": ["stitch", "thread", "patch", "knot"]
    },
    {
        "id": 24,
        "unit": 6,
        "unit_title": "Unit 6: Time and Work",
        "guardian": "⏳ Chrono Sphinx of Timeless Realms",
        "idiom": "all in good time",
        "clean_phrase": "all in good time",
        "meaning_en": "used to tell sb to be patient because the thing they are eager for will happen when the time is right",
        "meaning_vi": "sử dụng để nói rằng mọi thứ sẽ xảy ra vào đúng thời điểm của nó",
        "example": "Be patient with your exam results; you will hear from the admission committee all in good time.",
        "cloze_sentence": "Don't rush the publishing process; your debut novel will be released all in _____ time.",
        "cloze_options": ["good", "due", "best", "right"]
    },
    {
        "id": 25,
        "unit": 6,
        "unit_title": "Unit 6: Time and Work",
        "guardian": "⏳ Chrono Sphinx of Timeless Realms",
        "idiom": "at the drop of a hat",
        "clean_phrase": "at the drop of a hat",
        "meaning_en": "immediately, without hesitating",
        "meaning_vi": "ngay lập tức",
        "example": "He is so spontaneous that he would pack his bags and travel across the continent at the drop of a hat.",
        "cloze_sentence": "If you need emergency assistance, she will drive over at the drop of a _____.",
        "cloze_options": ["hat", "coin", "pin", "glove"]
    },
    {
        "id": 26,
        "unit": 6,
        "unit_title": "Unit 6: Time and Work",
        "guardian": "⏳ Chrono Sphinx of Timeless Realms",
        "idiom": "before sb's time",
        "clean_phrase": "before one's time",
        "meaning_en": "used for saying that sth happened or existed before you were born or before you lived or worked swh",
        "meaning_vi": "trước thời của ai đó",
        "example": "Floppy disks and dial-up internet were way before my time.",
        "cloze_sentence": "I know very little about 1960s vinyl records because that era was before my _____.",
        "cloze_options": ["time", "era", "age", "day"]
    },
    {
        "id": 27,
        "unit": 6,
        "unit_title": "Unit 6: Time and Work",
        "guardian": "⏳ Chrono Sphinx of Timeless Realms",
        "idiom": "for good",
        "clean_phrase": "for good",
        "meaning_en": "permanently, without the possibility of change in the future",
        "meaning_vi": "mãi mãi và không quay lại",
        "example": "After thirty years in London, she moved back to her coastal hometown for good.",
        "cloze_sentence": "He decided to shut down his social media accounts for _____.",
        "cloze_options": ["good", "ever", "all", "once"]
    },
    {
        "id": 28,
        "unit": 6,
        "unit_title": "Unit 6: Time and Work",
        "guardian": "⏳ Chrono Sphinx of Timeless Realms",
        "idiom": "for the time being",
        "clean_phrase": "for the time being",
        "meaning_en": "for now, at the present",
        "meaning_vi": "ngay bây giờ, hiện tại",
        "example": "We are renting a temporary flat for the time being until our new house is ready.",
        "cloze_sentence": "You can use my laptop for the time _____ while yours is in repair.",
        "cloze_options": ["being", "now", "present", "moment"]
    },
    {
        "id": 29,
        "unit": 6,
        "unit_title": "Unit 6: Time and Work",
        "guardian": "⏳ Chrono Sphinx of Timeless Realms",
        "idiom": "from time to time",
        "clean_phrase": "from time to time",
        "meaning_en": "sometimes, but not often",
        "meaning_vi": "đôi khi, thỉnh thoảng",
        "example": "We still meet up for a cup of coffee from time to time.",
        "cloze_sentence": "I still receive letters from my childhood pen pal from time to _____.",
        "cloze_options": ["time", "day", "now", "then"]
    },
    {
        "id": 30,
        "unit": 6,
        "unit_title": "Unit 6: Time and Work",
        "guardian": "⏳ Chrono Sphinx of Timeless Realms",
        "idiom": "in/for donkey's years",
        "clean_phrase": "for donkey's years",
        "meaning_en": "for a very long time",
        "meaning_vi": "một khoảng thời gian rất lâu",
        "example": "I haven't visited my grandparents' farm in donkey's years!",
        "cloze_sentence": "We haven't seen each other for _____ years; you look fantastic!",
        "cloze_options": ["donkey's", "horse's", "camel's", "dog's"]
    },
    {
        "id": 31,
        "unit": 6,
        "unit_title": "Unit 6: Time and Work",
        "guardian": "⏳ Chrono Sphinx of Timeless Realms",
        "idiom": "in the nick of time",
        "clean_phrase": "in the nick of time",
        "meaning_en": "at the last possible moment",
        "meaning_vi": "ngay những giây phút cuối",
        "example": "The firefighters arrived in the nick of time and rescued everyone trapped on the top floor.",
        "cloze_sentence": "He submitted his university assignment online in the _____ of time, just seconds before midnight.",
        "cloze_options": ["nick", "edge", "notch", "brink"]
    },
    {
        "id": 32,
        "unit": 6,
        "unit_title": "Unit 6: Time and Work",
        "guardian": "⏳ Chrono Sphinx of Timeless Realms",
        "idiom": "once in a blue moon",
        "clean_phrase": "once in a blue moon",
        "meaning_en": "very rarely",
        "meaning_vi": "rất hiếm, rất lâu mới xảy ra một lần",
        "example": "My brother lives abroad, so we only get to see him once in a blue moon.",
        "cloze_sentence": "Living in the sunny tropics, we experience snowfall only once in a _____ moon.",
        "cloze_options": ["blue", "red", "full", "silver"]
    },
    {
        "id": 33,
        "unit": 6,
        "unit_title": "Unit 6: Time and Work",
        "guardian": "⏳ Chrono Sphinx of Timeless Realms",
        "idiom": "on the spur of the moment",
        "clean_phrase": "on the spur of the moment",
        "meaning_en": "abrupt, describe a decision, action, etc that is sudden and done without any planning",
        "meaning_vi": "ngay lập tức mà không quan tâm đến việc lên kế hoạch",
        "example": "We booked the flight tickets to Tokyo on the spur of the moment without any prior itinerary.",
        "cloze_sentence": "She bought that expensive designer coat on the _____ of the moment.",
        "cloze_options": ["spur", "spark", "rush", "flash"]
    },
    {
        "id": 34,
        "unit": 6,
        "unit_title": "Unit 6: Time and Work",
        "guardian": "⏳ Chrono Sphinx of Timeless Realms",
        "idiom": "the other day",
        "clean_phrase": "the other day",
        "meaning_en": "recently",
        "meaning_vi": "dạo gần đây, một vài ngày trước",
        "example": "I ran into our former high school English teacher at the bookstore the other day.",
        "cloze_sentence": "I was browsing through old photo albums the _____ day and found our graduation picture.",
        "cloze_options": ["other", "next", "last", "past"]
    },

    # UNIT 8: MOVEMENT AND TRANSPORT (10 idioms)
    {
        "id": 35,
        "unit": 8,
        "unit_title": "Unit 8: Movement and Transport",
        "guardian": "🦅 Zephyr Falcon of Swift Horizons",
        "idiom": "a stone's throw (away/from)",
        "clean_phrase": "a stone's throw",
        "meaning_en": "very close (to), a very short distance",
        "meaning_vi": "rất gần một cái gì đó",
        "example": "Our new boutique hotel is just a stone's throw away from the golden sandy beach.",
        "cloze_sentence": "The train station is just a _____ throw away from our office.",
        "cloze_options": ["stone's", "rock's", "pebble's", "dart's"]
    },
    {
        "id": 36,
        "unit": 8,
        "unit_title": "Unit 8: Movement and Transport",
        "guardian": "🦅 Zephyr Falcon of Swift Horizons",
        "idiom": "as the crow flies",
        "clean_phrase": "as the crow flies",
        "meaning_en": "in a straight line (used for measuring distance)",
        "meaning_vi": "đường chim bay/ đường thẳng nối giữa 2 điểm mà không quan tâm vật cản",
        "example": "The distance between the two villages is only five miles as the crow flies, though the winding road takes twenty.",
        "cloze_sentence": "It is ten miles from here to the castle as the _____ flies.",
        "cloze_options": ["crow", "eagle", "dove", "hawk"]
    },
    {
        "id": 37,
        "unit": 8,
        "unit_title": "Unit 8: Movement and Transport",
        "guardian": "🦅 Zephyr Falcon of Swift Horizons",
        "idiom": "follow your nose",
        "clean_phrase": "follow your nose",
        "meaning_en": "go in a straight line / trust your own feelings rather than obeying rules or allowing yourself to be influenced by other people's opinion",
        "meaning_vi": "đi thẳng / tin tưởng vào bản năng, cảm tính của bản thân",
        "example": "To reach the ancient temple, just follow your nose along this paved path.",
        "cloze_sentence": "When you come to the crossroads in the forest, simply follow your _____.",
        "cloze_options": ["nose", "heart", "eyes", "instinct"]
    },
    {
        "id": 38,
        "unit": 8,
        "unit_title": "Unit 8: Movement and Transport",
        "guardian": "🦅 Zephyr Falcon of Swift Horizons",
        "idiom": "in the middle of nowhere",
        "clean_phrase": "in the middle of nowhere",
        "meaning_en": "describe a place far away from any towns or cities",
        "meaning_vi": "ở xa thành phố/đô thị lớn (nơi hẻo lánh, đồng không mông quạnh)",
        "example": "Our rental car broke down on a deserted dirt road right in the middle of nowhere.",
        "cloze_sentence": "They bought a serene cabin located right in the middle of _____.",
        "cloze_options": ["nowhere", "nothing", "wild", "forest"]
    },
    {
        "id": 39,
        "unit": 8,
        "unit_title": "Unit 8: Movement and Transport",
        "guardian": "🦅 Zephyr Falcon of Swift Horizons",
        "idiom": "lose your bearings",
        "clean_phrase": "lose one's bearings",
        "meaning_en": "if you lose your bearings, you do not know where you are",
        "meaning_vi": "không biết mình đang ở đâu, không xác định được vị trí của bản thân (mất phương hướng)",
        "example": "In the dense fog on the mountain summit, the hikers easily lost their bearings.",
        "cloze_sentence": "Without a compass or GPS signal in the blizzard, it is easy to lose your _____.",
        "cloze_options": ["bearings", "directions", "tracks", "headings"]
    },
    {
        "id": 40,
        "unit": 8,
        "unit_title": "Unit 8: Movement and Transport",
        "guardian": "🦅 Zephyr Falcon of Swift Horizons",
        "idiom": "make a beeline for",
        "clean_phrase": "make a beeline for",
        "meaning_en": "go directly and quickly towards sb or sth",
        "meaning_vi": "đi nhanh và trực tiếp đến một thứ gì đó hoặc một người khác",
        "example": "As soon as the school bell rang, the kids made a beeline for the ice cream truck.",
        "cloze_sentence": "Exhausted after the long flight, she made a _____ for the hotel bed.",
        "cloze_options": ["beeline", "pathway", "flight", "dash"]
    },
    {
        "id": 41,
        "unit": 8,
        "unit_title": "Unit 8: Movement and Transport",
        "guardian": "🦅 Zephyr Falcon of Swift Horizons",
        "idiom": "off the beaten track/path",
        "clean_phrase": "off the beaten track",
        "meaning_en": "in a place where few people go, far from any main roads and towns/in or into an isolated place",
        "meaning_vi": "hẻo lánh, xa những thành phố và ít người biết tới",
        "example": "We love backpacking in secluded places that are off the beaten track.",
        "cloze_sentence": "We discovered a charming seafood restaurant tucked away off the beaten _____.",
        "cloze_options": ["track", "route", "highway", "trail"]
    },
    {
        "id": 42,
        "unit": 8,
        "unit_title": "Unit 8: Movement and Transport",
        "guardian": "🦅 Zephyr Falcon of Swift Horizons",
        "idiom": "stop dead in sb's tracks",
        "clean_phrase": "stop dead in one's tracks",
        "meaning_en": "suddenly stop, for example because you are surprised or alarmed",
        "meaning_vi": "đột nhiên dừng lại (sững sờ, đứng hình)",
        "example": "When she heard the sudden sound of shattering glass, she stopped dead in her tracks.",
        "cloze_sentence": "The unexpected roar from behind made him stop dead in his _____.",
        "cloze_options": ["tracks", "steps", "feet", "shoes"]
    },
    {
        "id": 43,
        "unit": 8,
        "unit_title": "Unit 8: Movement and Transport",
        "guardian": "🦅 Zephyr Falcon of Swift Horizons",
        "idiom": "take a short cut to",
        "clean_phrase": "take a short cut",
        "meaning_en": "follow a path that is quicker and shorter than the usual way",
        "meaning_vi": "đi đường tắt thay vì đường bình thường",
        "example": "If we take a short cut through the park, we'll reach the station ten minutes earlier.",
        "cloze_sentence": "We managed to avoid the traffic gridlock by taking a short _____ through the alleyways.",
        "cloze_options": ["cut", "way", "pass", "line"]
    },
    {
        "id": 44,
        "unit": 8,
        "unit_title": "Unit 8: Movement and Transport",
        "guardian": "🦅 Zephyr Falcon of Swift Horizons",
        "idiom": "take the scenic route",
        "clean_phrase": "take the scenic route",
        "meaning_en": "follow a longer path than the usual one because it is more attractive",
        "meaning_vi": "đi một đoạn đường dài hơn (đi đường vòng) vì cảnh đẹp hơn",
        "example": "Instead of speeding down the highway, let's take the scenic route along the coastline.",
        "cloze_sentence": "Since we have all afternoon, let's take the _____ route through the mountain valley.",
        "cloze_options": ["scenic", "pretty", "view", "nature"]
    },

    # UNIT 10: COMMUNICATION AND THE MEDIA (12 idioms)
    {
        "id": 45,
        "unit": 10,
        "unit_title": "Unit 10: Communication and the Media",
        "guardian": "📜 Whispering Pixie of Truth",
        "idiom": "big mouth",
        "clean_phrase": "big mouth",
        "meaning_en": "used as a criticism of sb when they say things they should not",
        "meaning_vi": "sử dụng để chỉ trích ai đó khi họ nói những điều mà họ không nên (kẻ nhiều chuyện, bép xép)",
        "example": "Don't tell Mark about the surprise party; he has such a big mouth!",
        "cloze_sentence": "Never share your confidential secrets with her because she has a _____ mouth.",
        "cloze_options": ["big", "loud", "wide", "tall"]
    },
    {
        "id": 46,
        "unit": 10,
        "unit_title": "Unit 10: Communication and the Media",
        "guardian": "📜 Whispering Pixie of Truth",
        "idiom": "come clean (about sth)",
        "clean_phrase": "come clean",
        "meaning_en": "tell the truth about sth that you have kept secret",
        "meaning_vi": "nói ra sự thật mà bản thân đã giữ bí mật (thú nhận)",
        "example": "The politician finally came clean about the undisclosed campaign funding.",
        "cloze_sentence": "It is always better to come _____ and confess than to keep covering up your mistakes.",
        "cloze_options": ["clean", "clear", "pure", "true"]
    },
    {
        "id": 47,
        "unit": 10,
        "unit_title": "Unit 10: Communication and the Media",
        "guardian": "📜 Whispering Pixie of Truth",
        "idiom": "get/catch sb's drift",
        "clean_phrase": "catch someone's drift",
        "meaning_en": "understand the general meaning of what sb is saying",
        "meaning_vi": "hiểu được khái quát về thứ mà ai đó đang nói/giảng",
        "example": "I'm not saying he stole the files, but you catch my drift, don't you?",
        "cloze_sentence": "He hinted at budget cuts without naming numbers, but everyone caught his _____.",
        "cloze_options": ["drift", "tide", "flow", "wind"]
    },
    {
        "id": 48,
        "unit": 10,
        "unit_title": "Unit 10: Communication and the Media",
        "guardian": "📜 Whispering Pixie of Truth",
        "idiom": "get sth off sb's chest",
        "clean_phrase": "get sth off one's chest",
        "meaning_en": "tell sb about sth has been worrying you or making you feel guilty for a long time",
        "meaning_vi": "trải lòng/ chia sẻ với ai đó về điều đã khiến bản thân lo lắng hay cảm thấy hối hận trong một thời gian dài",
        "example": "She felt a tremendous sense of relief after getting the truth off her chest.",
        "cloze_sentence": "You look troubled; talk to a trusted friend and get it off your _____.",
        "cloze_options": ["chest", "heart", "mind", "head"]
    },
    {
        "id": 49,
        "unit": 10,
        "unit_title": "Unit 10: Communication and the Media",
        "guardian": "📜 Whispering Pixie of Truth",
        "idiom": "get the wrong end of the stick",
        "clean_phrase": "get the wrong end of the stick",
        "meaning_en": "misunderstand sth, understand sth completely wrongly",
        "meaning_vi": "không hiểu hoàn toàn bản chất của vấn đề/ hiểu lệch hoàn toàn một thứ gì đó",
        "example": "You've got the wrong end of the stick; I wasn't criticizing your project, I was praising it!",
        "cloze_sentence": "She got the wrong end of the _____ and assumed she was fired when she was actually promoted.",
        "cloze_options": ["stick", "rope", "pole", "wire"]
    },
    {
        "id": 50,
        "unit": 10,
        "unit_title": "Unit 10: Communication and the Media",
        "guardian": "📜 Whispering Pixie of Truth",
        "idiom": "give (sb) your word",
        "clean_phrase": "give someone your word",
        "meaning_en": "promise to do sth",
        "meaning_vi": "hứa với ai đó",
        "example": "I give you my word that the project will be delivered before Friday afternoon.",
        "cloze_sentence": "He gave us his _____ that all client information would remain strictly confidential.",
        "cloze_options": ["word", "voice", "pledge", "hand"]
    },
    {
        "id": 51,
        "unit": 10,
        "unit_title": "Unit 10: Communication and the Media",
        "guardian": "📜 Whispering Pixie of Truth",
        "idiom": "(hear sth) on/through the grapevine",
        "clean_phrase": "hear on the grapevine",
        "meaning_en": "hear news from sb who heard the news from sb else (informal rumor or gossip)",
        "meaning_vi": "nghe được tin tức lan truyền từ người này sang người kia (nghe đồn)",
        "example": "I heard through the grapevine that our manager is moving to the Paris branch.",
        "cloze_sentence": "We heard on the _____ that a new product launch is scheduled for next quarter.",
        "cloze_options": ["grapevine", "pipeline", "wireline", "headline"]
    },
    {
        "id": 52,
        "unit": 10,
        "unit_title": "Unit 10: Communication and the Media",
        "guardian": "📜 Whispering Pixie of Truth",
        "idiom": "keep sb posted (on sth)",
        "clean_phrase": "keep sb posted",
        "meaning_en": "make sure that sb always knows what is happening",
        "meaning_vi": "giúp ai đó nắm bắt chuyện gì đang xảy ra (cập nhật tình hình thường xuyên)",
        "example": "Please keep me posted on any developments regarding the negotiation.",
        "cloze_sentence": "I'll be traveling next week, so keep me _____ on the lab experiment results via email.",
        "cloze_options": ["posted", "mailed", "noted", "tracked"]
    },
    {
        "id": 53,
        "unit": 10,
        "unit_title": "Unit 10: Communication and the Media",
        "guardian": "📜 Whispering Pixie of Truth",
        "idiom": "keep sth under sb's hat",
        "clean_phrase": "keep sth under one's hat",
        "meaning_en": "keep sth secret",
        "meaning_vi": "giữ bí mật",
        "example": "We are launching a groundbreaking app next month, but keep it under your hat for now.",
        "cloze_sentence": "I'll share this confidential insight with you, provided you keep it under your _____.",
        "cloze_options": ["hat", "cap", "hood", "cloak"]
    },
    {
        "id": 54,
        "unit": 10,
        "unit_title": "Unit 10: Communication and the Media",
        "guardian": "📜 Whispering Pixie of Truth",
        "idiom": "lay/put sb's cards on the table",
        "clean_phrase": "put one's cards on the table",
        "meaning_en": "be honest about your feelings and intentions",
        "meaning_vi": "trở nên trung thực về ý định và cảm xúc (ngửa bài, thẳng thắn)",
        "example": "Let's put our cards on the table and discuss what each party truly expects from this partnership.",
        "cloze_sentence": "It is time to put our _____ on the table and negotiate with complete transparency.",
        "cloze_options": ["cards", "coins", "hands", "chips"]
    },
    {
        "id": 55,
        "unit": 10,
        "unit_title": "Unit 10: Communication and the Media",
        "guardian": "📜 Whispering Pixie of Truth",
        "idiom": "speak volumes",
        "clean_phrase": "speak volumes",
        "meaning_en": "if sth speaks volumes, it makes an opinion, characteristic, or situation very clear without using the use of words",
        "meaning_vi": "nói ra được ý định nhưng không thông qua ngôn ngữ / ngụ ý (nói lên rất nhiều điều)",
        "example": "Her sudden silence and warm smile spoke volumes about her genuine feelings.",
        "cloze_sentence": "His outstanding commitment and punctuality speak _____ for his professional work ethic.",
        "cloze_options": ["volumes", "novels", "words", "echoes"]
    },
    {
        "id": 56,
        "unit": 10,
        "unit_title": "Unit 10: Communication and the Media",
        "guardian": "📜 Whispering Pixie of Truth",
        "idiom": "tell tales",
        "clean_phrase": "tell tales",
        "meaning_en": "tell sb in authority about bad things that else has done, because you want them to be punished",
        "meaning_vi": "mách lẻo, để lộ ra điều xấu mà ai đó hoặc có thể đã làm",
        "example": "Stop telling tales about your classmates to the teacher; solve your disputes maturely.",
        "cloze_sentence": "Children are often reprimanded if they constantly tell _____ out of school.",
        "cloze_options": ["tales", "stories", "fables", "myths"]
    },

    # UNIT 12: CHANCE AND NATURE (5 idioms)
    {
        "id": 57,
        "unit": 12,
        "unit_title": "Unit 12: Chance and Nature",
        "guardian": "🍀 Gaia Forest Nymph of Destiny",
        "idiom": "an act of God",
        "clean_phrase": "an act of God",
        "meaning_en": "a natural event that cannot be controlled or prevented by humans, especially one that causes a lot of damage, such as an earthquake or a flood",
        "meaning_vi": "hiện tượng thiên nhiên mà con người không thể kiểm soát (thiên tai bất khả kháng)",
        "example": "The insurance policy covered fire and theft, but excluded damage caused by an act of God.",
        "cloze_sentence": "The flash flood was deemed an act of _____ by the insurance evaluators.",
        "cloze_options": ["God", "Nature", "Fate", "Earth"]
    },
    {
        "id": 58,
        "unit": 12,
        "unit_title": "Unit 12: Chance and Nature",
        "guardian": "🍀 Gaia Forest Nymph of Destiny",
        "idiom": "come rain or shine",
        "clean_phrase": "come rain or shine",
        "meaning_en": "whatever happens",
        "meaning_vi": "dù cho có chuyện gì xảy ra đi chăng nữa (bất kể mưa nắng)",
        "example": "I will be there at the finish line to cheer for you, come rain or shine!",
        "cloze_sentence": "The outdoor charity marathon will proceed as scheduled, come rain or _____.",
        "cloze_options": ["shine", "sun", "storm", "snow"]
    },
    {
        "id": 59,
        "unit": 12,
        "unit_title": "Unit 12: Chance and Nature",
        "guardian": "🍀 Gaia Forest Nymph of Destiny",
        "idiom": "down on your luck",
        "clean_phrase": "down on one's luck",
        "meaning_en": "having a long period of difficulty finding work and earning money",
        "meaning_vi": "trải qua thời kỳ khó khăn, thiếu thốn tiền bạc, công việc không ổn định (gặp vận rủi)",
        "example": "The community shelter provides warm meals and shelter for people down on their luck.",
        "cloze_sentence": "He was down on his _____ after losing his job, but never lost his optimism.",
        "cloze_options": ["luck", "fate", "chance", "money"]
    },
    {
        "id": 60,
        "unit": 12,
        "unit_title": "Unit 12: Chance and Nature",
        "guardian": "🍀 Gaia Forest Nymph of Destiny",
        "idiom": "draw the short straw",
        "clean_phrase": "draw the short straw",
        "meaning_en": "be chosen to do sth unpleasant",
        "meaning_vi": "được chọn để làm những việc khó khăn, gây khó chịu (bốc phải lá thăm xấu)",
        "example": "I drew the short straw and had to clean up the science laboratory after everyone left.",
        "cloze_sentence": "Someone has to work the midnight shift this weekend, and poor Leo drew the short _____.",
        "cloze_options": ["straw", "stick", "card", "leaf"]
    },
    {
        "id": 61,
        "unit": 12,
        "unit_title": "Unit 12: Chance and Nature",
        "guardian": "🍀 Gaia Forest Nymph of Destiny",
        "idiom": "have green fingers",
        "clean_phrase": "have green fingers",
        "meaning_en": "be good at growing plants",
        "meaning_vi": "có khả năng trồng / nuôi dưỡng cây cối tốt (mát tay trồng trọt)",
        "example": "Her balcony is filled with blossoming roses and lush orchids because she has green fingers.",
        "cloze_sentence": "Everything in Grandma's botanical garden thrives because she really has _____ fingers.",
        "cloze_options": ["green", "gold", "floral", "leafy"]
    }
]

units_meta = [
    {
        "id": 2,
        "title": "Unit 2: Thinking and Learning",
        "desc": "12 Cụm thành ngữ về tư duy, quan sát, phán đoán và tiếp thu kiến thức.",
        "guardian": "🦉 Athena Owl of Wisdom",
        "icon": "🦉",
        "theme_color": "#38bdf8",
        "range": [1, 12]
    },
    {
        "id": 4,
        "title": "Unit 4: Change and Technology",
        "desc": "10 Cụm thành ngữ về sự chuyển biến, đổi mới công nghệ và thái độ sống.",
        "guardian": "⚡ Cyber Phoenix of Innovation",
        "icon": "⚡",
        "theme_color": "#f59e0b",
        "range": [13, 22]
    },
    {
        "id": 6,
        "title": "Unit 6: Time and Work",
        "desc": "12 Cụm thành ngữ về thời gian, cơ hội, tính kiên nhẫn và phong cách làm việc.",
        "guardian": "⏳ Chrono Sphinx of Timeless Realms",
        "icon": "⏳",
        "theme_color": "#10b981",
        "range": [23, 34]
    },
    {
        "id": 8,
        "title": "Unit 8: Movement and Transport",
        "desc": "10 Cụm thành ngữ về phương hướng, hành trình di chuyển và khám phá.",
        "guardian": "🦅 Zephyr Falcon of Swift Horizons",
        "icon": "🦅",
        "theme_color": "#ec4899",
        "range": [35, 44]
    },
    {
        "id": 10,
        "title": "Unit 10: Communication and Media",
        "desc": "12 Cụm thành ngữ về giao tiếp, tin đồn, chia sẻ bí mật và độ chân thực.",
        "guardian": "📜 Whispering Pixie of Truth",
        "icon": "📜",
        "theme_color": "#a855f7",
        "range": [45, 56]
    },
    {
        "id": 12,
        "title": "Unit 12: Chance and Nature",
        "desc": "5 Cụm thành ngữ về thiên nhiên, sự may rủi, số phận và bản lĩnh.",
        "guardian": "🍀 Gaia Forest Nymph of Destiny",
        "icon": "🍀",
        "theme_color": "#22c55e",
        "range": [57, 61]
    }
]

print("Total idioms:", len(idioms_data))
assert len(idioms_data) == 61
